<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 16:40:12
?>
<?php use_helper('Object') ?>

<?php echo form_tag('cargo/update') ?>

<?php echo object_input_hidden_tag($cargo, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Nombre:</th>
  <td><?php echo object_input_tag($cargo, 'getNombre', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Dependencia:</th>
  <td><?php echo object_select_tag($cargo, 'getDependenciaId', array (
  'related_class' => 'Dependencia',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($cargo->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'cargo/delete?id='.$cargo->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'cargo/show?id='.$cargo->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'cargo/list') ?>
<?php endif; ?>
</form>
