<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 16:40:12
?>
<?php use_helper('Object') ?>

<?php echo form_tag('cargo/update') ?>

<?php echo object_input_hidden_tag($cargo, 'getId') ?>

<table class="data">
<tbody>
<tr>
  <th>Nombre:</th>
  <td><?php echo object_input_tag($cargo, 'getNombre', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Dependencia:</th>
  <td><?php echo object_select_tag($cargo, 'getDependenciaId', array (
  'related_class' => 'Dependencia',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($cargo->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'cargo/delete?id='.$cargo->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'cargo/show?id='.$cargo->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'cargo/list') ?>
<?php endif; ?>
</form>
