<?php
// auto-generated by sfPropelCrud
// date: 2009/02/04 17:11:54
?>
<h1>Indicador</h1>

<table>
<thead>
<tr>
  <th>Indicador</th>
  <th>Objetivo</th>
  <th>Categoria</th>
  <th>Formula</th>
  <th>Frecuencia</th>
</tr>
</thead>
<tbody>
<?php foreach ($indicadors as $i => $indicador): ?>
<tr class="<?php echo fmod($i, 2) ? 'par' : 'impar' ?>">
    <td><?php echo link_to($indicador->getIndicador(), 'indicador/createformula?id='.$indicador->getId()) ?></td>
      <td><?php echo $indicador->getObjetivo() ?></td>
      <td><?php echo $indicador->getCategoria() ?></td>
      <td><?php echo $indicador->getFormulaTextual() ?></td>
      <td><?php echo $indicador->getFrecuencia() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
