<?php
// auto-generated by sfPropelCrud
// date: 2009/02/04 17:11:54
?>
<table class="data">
<tbody>
<tr>
<th>Indicador: </th>
<td><?php echo $indicador->getIndicador() ?></td>
</tr>
<tr>
<th>Borrador: </th>
<td><?php echo $indicador->getBorrador() ?></td>
</tr>
<tr>
<th>Objetivo Estrategico: </th>
<td><?php echo $indicador->getObjetivo() ?></td>
</tr>
<tr>
<th>Objetivo del indicador: </th>
<td><?php echo $indicador->getObjetivoEstr() ?></td>
</tr>
<tr>
<th>Categoria: </th>
<td><?php echo $indicador->getCategoriaId() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $indicador->getDescripcion() ?></td>
</tr>
<tr>
<th>Formula textual: </th>
<td><?php echo $indicador->getFormulaTextual() ?></td>
</tr>
<tr>
<th>Tipo: </th>
<td><?php echo $indicador->getTipo() ?></td>
</tr>
<tr>
<th>Frecuencia: </th>
<td><?php echo $indicador->getFrecuencia() ?></td>
</tr>
<tr>
<th>Responsable: </th>
<td><?php echo $indicador->getResponsableId() ?></td>
</tr>
<tr>
<th>Umbral rojo: </th>
<td><?php echo $indicador->getUmbralRojo() ?></td>
</tr>
<tr>
<th>Umbral amarillo: </th>
<td><?php echo $indicador->getUmbralAmarillo() ?></td>
</tr>
<tr>
<th>Umbral verde: </th>
<td><?php echo $indicador->getUmbralVerde() ?></td>
</tr>
<tr>
<th>Meta: </th>
<td><?php echo $indicador->getMeta() ?></td>
</tr>
<tr>
<th>Iniciativa: </th>
<td><?php echo $indicador->getIniciativa() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Modificar', 'indicador/edit?id='.$indicador->getId(), 'class="button"') ?>
&nbsp;<?php echo link_to('Regresar a la lista', 'indicador/list', 'class="button"') ?>
