<?php
// auto-generated by sfPropelCrud
// date: 2010/09/20 23:38:20
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $subactividad_poa->getId() ?></td>
</tr>
<tr>
<th>Procedimiento: </th>
<td><?php echo $subactividad_poa->getProcedimientoId() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $subactividad_poa->getDescripcion() ?></td>
</tr>
<tr>
<th>Responsable: </th>
<td><?php echo $subactividad_poa->getResponsable() ?></td>
</tr>
<tr>
<th>Entregable: </th>
<td><?php echo $subactividad_poa->getEntregable() ?></td>
</tr>
<tr>
<th>Fecha inicio: </th>
<td><?php echo $subactividad_poa->getFechaInicio() ?></td>
</tr>
<tr>
<th>Duracion: </th>
<td><?php echo $subactividad_poa->getDuracion() ?></td>
</tr>
<tr>
<th>Ponderacion: </th>
<td><?php echo $subactividad_poa->getPonderacion() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $subactividad_poa->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $subactividad_poa->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'subactividadpoa/edit?id='.$subactividad_poa->getId()) ?>
&nbsp;<?php echo link_to('Listar', 'subactividadpoa/list') ?>
