<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:13:51
?>
<?php

/**
 * clienteactividad actions.
 *
 * @package    indicadores
 * @subpackage clienteactividad
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class clienteactividadActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('clienteactividad', 'list');
  }

  public function executeList()
  {
    // listar las fuentes de la actividad seleccionada
    if($this->getRequestParameter('actividad')) {
      $c = new Criteria();
      $c->add(ClienteActividadPeer::ACTIVIDAD_ID, $this->getRequestParameter('actividad'));

      $this->cliente_actividads = ClienteActividadPeer::doSelect($c);

    // mostrar la lista de actividades correspondiente al proyecto y mes
    } elseif (($this->getRequestParameter('proyecto')) && ($this->getRequestParameter('mes'))) {
      $c = new Criteria();
      $c->add(ActividadPeer::PROYECTO_ID, $this->getRequestParameter('proyecto'));
      $c->add(ActividadPeer::MES_INICIO_EJECUCION, $this->getRequestParameter('mes'));

      $this->actividads = ActividadPeer::doSelect($c);

      $this->setTemplate('ListActividades');
    // mostrar formulario de busqueda de actividad
    } else {
      $this->setTemplate('BuscarActividad');

    }
    $this->cliente_actividads = ClienteActividadPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->cliente_actividad = ClienteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->cliente_actividad);
  }

  public function executeCreate()
  {
    if($this->getRequestParameter('actividad')) {
      $this->cliente_actividad = new ClienteActividad();
      $this->actividad = ActividadPeer::retrieveByPK($this->getRequestParameter('actividad'));

      $this->setTemplate('edit');

    } elseif (($this->getRequestParameter('proyecto')) && ($this->getRequestParameter('mes'))) {
      $c = new Criteria();
      $c->add(ActividadPeer::PROYECTO_ID, $this->getRequestParameter('proyecto'));
      $c->add(ActividadPeer::MES_INICIO_EJECUCION, $this->getRequestParameter('mes'));

      $this->actividads = ActividadPeer::doSelect($c);

      $this->setTemplate('ListActividadesCreate');
    // mostrar formulario de busqueda de actividad
    } else {
      $this->setTemplate('BuscarActividadCreate');

    }
  }

  public function executeEdit()
  {
    $this->cliente_actividad = ClienteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->actividad = ActividadPeer::retrieveByPK($this->getRequestParameter('actividad'));
    $this->forward404Unless($this->cliente_actividad);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $cliente_actividad = new ClienteActividad();
    }
    else
    {
      $cliente_actividad = ClienteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($cliente_actividad);
    }

    $cliente_actividad->setId($this->getRequestParameter('id'));
    $cliente_actividad->setClienteId($this->getRequestParameter('cliente_id') ? $this->getRequestParameter('cliente_id') : null);
    $cliente_actividad->setActividadId($this->getRequestParameter('actividad_id') ? $this->getRequestParameter('actividad_id') : null);
    $cliente_actividad->setMonto($this->getRequestParameter('monto'));
    $cliente_actividad->setCantidad($this->getRequestParameter('cantidad'));

    $cliente_actividad->save();

    return $this->redirect('clienteactividad/show?id='.$cliente_actividad->getId());
  }

  public function executeDelete()
  {
    $cliente_actividad = ClienteActividadPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($cliente_actividad);

    $cliente_actividad->delete();

    return $this->redirect('clienteactividad/list');
  }
}
