<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 15:34:56
?>
<?php

/**
 * proceso actions.
 *
 * @package    indicadores
 * @subpackage proceso
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class procesoActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('proceso', 'list');
  }

  public function executeList()
  {
    $this->procesos = ProcesoPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->proceso = ProcesoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->proceso);
  }

  public function executeCreate()
  {
    $this->proceso = new Proceso();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->proceso = ProcesoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->proceso);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $proceso = new Proceso();
    }
    else
    {
      $proceso = ProcesoPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($proceso);
    }

    $proceso->setId($this->getRequestParameter('id'));
    $proceso->setMacroprocesoId($this->getRequestParameter('macroproceso_id') ? $this->getRequestParameter('macroproceso_id') : null);
    $proceso->setNombre($this->getRequestParameter('nombre'));
    $proceso->setCargoId($this->getRequestParameter('cargo_id') ? $this->getRequestParameter('cargo_id') : null);
    $proceso->setDescripcion($this->getRequestParameter('descripcion'));

    $proceso->save();

    return $this->redirect('proceso/show?id='.$proceso->getId());
  }

  public function executeDelete()
  {
    $proceso = ProcesoPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($proceso);

    $proceso->delete();

    return $this->redirect('proceso/list');
  }
}
