<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:15:18
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $crp_actividad->getId() ?></td>
</tr>
<tr>
<th>Crp: </th>
<td><?php echo $crp_actividad->getCrpId() ?></td>
</tr>
<tr>
<th>Actividad: </th>
<td><?php echo $crp_actividad->getActividadId() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'crpactividad/edit?id='.$crp_actividad->getId()) ?>
&nbsp;<?php echo link_to('Listar', 'crpactividad/list') ?>
