<?php
// auto-generated by sfPropelCrud
// date: 2010/08/27 15:42:00
?>
<h1>seguimientometas</h1>

<table class="data">
<thead>
<tr>
  <th>Id</th>
  <th>Indicador meta</th>
  <th>Anyo</th>
  <th>Valor</th>
</tr>
</thead>
<tbody>
<?php foreach ($seguimiento_indicador_metas as $seguimiento_indicador_meta): ?>
<tr>
    <td><?php echo link_to($seguimiento_indicador_meta->getId(), 'seguimientometas/show?id='.$seguimiento_indicador_meta->getId()) ?></td>
      <td><?php echo $seguimiento_indicador_meta->getIndicadorMetaId() ?></td>
      <td><?php echo $seguimiento_indicador_meta->getAnyo() ?></td>
      <td><?php echo $seguimiento_indicador_meta->getValor() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'seguimientometas/create') ?>
