<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:23:50
?>
<?php use_helper('Object') ?>

<?php echo form_tag('metapoa/update') ?>

<?php echo object_input_hidden_tag($meta_poa, 'getId') ?>

<table class="data">
<tbody>
<tr>
  <th>Meta*:</th>
  <td><?php echo object_input_tag($meta_poa, 'getMeta', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Descripcion*:</th>
  <td><?php echo object_textarea_tag($meta_poa, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($meta_poa->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'metapoa/delete?id='.$meta_poa->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'metapoa/show?id='.$meta_poa->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'metapoa/list') ?>
<?php endif; ?>
</form>
