<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:19:50
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $meta_poa->getId() ?></td>
</tr>
<tr>
<th>Meta: </th>
<td><?php echo $meta_poa->getMeta() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $meta_poa->getDescripcion() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $meta_poa->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $meta_poa->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'metapoa/edit?id='.$meta_poa->getId()) ?>
&nbsp;<?php echo link_to('list', 'metapoa/list') ?>
