<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:14:04
?>
<?php use_helper('Object') ?>

<?php echo form_tag('metaproyecto/update') ?>

<?php echo object_input_hidden_tag($meta_proyecto, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Meta pd:</th>
  <td><?php echo object_select_tag($meta_proyecto, 'getMetaPdId', array (
  'related_class' => 'MetaPd',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Codigo:</th>
  <td><?php echo object_input_tag($meta_proyecto, 'getCodigo', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Meta:</th>
  <td><?php echo object_input_tag($meta_proyecto, 'getMeta', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($meta_proyecto, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($meta_proyecto->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'metaproyecto/delete?id='.$meta_proyecto->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'metaproyecto/show?id='.$meta_proyecto->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'metaproyecto/list') ?>
<?php endif; ?>
</form>
