<?php
// auto-generated by sfPropelCrud
// date: 2010/08/03 01:29:27
?>
<?php use_helper('Object') ?>

<?php echo form_tag('metaproyecto/update') ?>

<?php echo object_input_hidden_tag($meta_proyecto, 'getId') ?>

<table class="data">
<tbody>
<tr>
  <th>Meta pd:</th>
  <td><?php echo object_select_tag($meta_proyecto, 'getMetaPdId', array (
  'related_class' => 'MetaPd',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Proyecto:</th>
  <td><?php echo object_select_tag($meta_proyecto, 'getProyectoId', array (
  'related_class' => 'Proyecto',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Codigo*:</th>
  <td><?php echo object_input_tag($meta_proyecto, 'getCodigo', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Meta:</th>
  <td><?php echo object_input_tag($meta_proyecto, 'getMeta', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Tipo:</th>
  <td><?php echo object_input_tag($meta_proyecto, 'getTipo', array (
  'size' => 25,
)) ?></td>
</tr>
<tr>
  <th>Objetivo:</th>
  <td><?php echo object_select_tag($meta_proyecto, 'getObjetivoId', array (
  'related_class' => 'Objetivo',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($meta_proyecto, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Anualizacion:</th>
  <td><?php echo object_select_tag($meta_proyecto, 'getAnualizacionId', array (
  'related_class' => 'Anualizacion',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($meta_proyecto->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'metaproyecto/delete?id='.$meta_proyecto->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'metaproyecto/show?id='.$meta_proyecto->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'metaproyecto/list') ?>
<?php endif; ?>
</form>
