<?php
// auto-generated by sfPropelCrud
// date: 2010/07/15 21:17:05
?>
<h1>metaproyecto</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Meta pd</th>
  <th>Proyecto</th>
  <th>Codigo</th>
  <th>Meta</th>
  <th>Descripcion</th>
  <th>Anualizacion</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($meta_proyectos as $meta_proyecto): ?>
<tr>
    <td><?php echo link_to($meta_proyecto->getId(), 'metaproyecto/show?id='.$meta_proyecto->getId()) ?></td>
      <td><?php echo $meta_proyecto->getMetaPdId() ?></td>
      <td><?php echo $meta_proyecto->getProyectoId() ?></td>
      <td><?php echo $meta_proyecto->getCodigo() ?></td>
      <td><?php echo $meta_proyecto->getMeta() ?></td>
      <td><?php echo $meta_proyecto->getDescripcion() ?></td>
      <td><?php echo $meta_proyecto->getAnualizacionId() ?></td>
      <td><?php echo $meta_proyecto->getCreatedAt() ?></td>
      <td><?php echo $meta_proyecto->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'metaproyecto/create') ?>
