<?php
// auto-generated by sfPropelCrud
// date: 2010/08/03 01:29:27
?>
<h1>Metas de Proyecto</h1>

<table class="data">
<thead>
<tr>
  <th>Codigo</th>
  <th>Meta Plan Desarrollo</th>
  <th>Proyecto</th>
  <th>Meta</th>
  <th>Tipo</th>
  <th>Objetivo</th>
  <th>Descripcion</th>
  <th>Anualizacion</th>
</tr>
</thead>
<tbody>
<?php foreach ($meta_proyectos as $meta_proyecto): ?>
<tr>
    <td><?php echo link_to($meta_proyecto->getCodigo(), 'metaproyecto/show?id='.$meta_proyecto->getId()) ?></td>
      <td><?php echo $meta_proyecto->getMetaPd() ?></td>
      <td><?php echo $meta_proyecto->getProyecto() ?></td>
      <td><?php echo $meta_proyecto->getMeta() ?></td>
      <td><?php echo $meta_proyecto->getTipo() ?></td>
      <td><?php echo $meta_proyecto->getObjetivoId() ?></td>
      <td><?php echo $meta_proyecto->getDescripcion() ?></td>
      <td><?php echo $meta_proyecto->getAnualizacionId() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
