# default rules
homepage:
  url:   /
  param: { module: menu, action: index }
  
sf_guard_signout:
  url:   /signout
  param: { module: sfGuardAuth, action: signout }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  


