default:
  http_metas:
    content-type: text/html

  metas:
    title:        FVS - Sistema de Medicion de Indicadores
    robots:       index, nofollow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [tablecloth, main, styles, menu, button]

  javascripts:    [yahoo-dom-event, container-min, menu-min, element-beta-min, button-min, functions, tablecloth]

  has_layout:     on
  layout:         layout
