<?php
// auto-generated by sfPropelCrud
// date: 2009/02/04 17:12:26
?>
<?php use_helper('Object') ?>

<?php echo form_tag('variable/update') ?>

<?php echo object_input_hidden_tag($variable, 'getId') ?>

<table class="data">
<tbody>
<tr>
  <th>Nombre:</th>
  <td><?php echo object_input_tag($variable, 'getNombre', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Descripci&oacute;n:</th>
  <td><?php echo object_textarea_tag($variable, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($variable->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'variable/delete?id='.$variable->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'variable/show?id='.$variable->getId(), 'class="button"') ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'variable/list', 'class="button"') ?>
<?php endif; ?>
</form>
