<?php
// auto-generated by sfPropelCrud
// date: 2009/02/04 17:12:26
?>
<h1>variable</h1>

<table class="data">
<thead>
<tr>
  <th>Nombre</th>
  <th>Descripcion</th>
</tr>
</thead>
<tbody>
<?php foreach ($variables as $i => $variable): ?>
<tr class="<?php echo fmod($i, 2) ? 'par' : 'impar' ?>">
    <td><?php echo link_to($variable->getNombre(), 'variable/show?id='.$variable->getId()) ?></td>
      <td><?php echo $variable->getDescripcion() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
