<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:21:47
?>
<?php use_helper('Object') ?>

<?php echo form_tag('localidadact/update') ?>

<?php echo object_input_hidden_tag($localidad_actividad, 'getId') ?>

<table class="data">
<tbody>
<tr>
  <th>Localidad:</th>
  <td><?php echo object_select_tag($localidad_actividad, 'getLocalidadId', array (
  'related_class' => 'Localidad',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Actividad:</th>
  <td><?php echo object_select_tag($localidad_actividad, 'getActividadId', array (
  'related_class' => 'Actividad',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Monto:</th>
  <td><?php echo object_input_tag($localidad_actividad, 'getMonto', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Cantidad:</th>
  <td><?php echo object_input_tag($localidad_actividad, 'getCantidad', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($localidad_actividad->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'localidadact/delete?id='.$localidad_actividad->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'localidadact/show?id='.$localidad_actividad->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'localidadact/list') ?>
<?php endif; ?>
</form>
