<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:21:47
?>
<h1>localidadact</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Localidad</th>
  <th>Actividad</th>
  <th>Monto</th>
  <th>Cantidad</th>
</tr>
</thead>
<tbody>
<?php foreach ($localidad_actividads as $localidad_actividad): ?>
<tr>
    <td><?php echo link_to($localidad_actividad->getId(), 'localidadact/show?id='.$localidad_actividad->getId()) ?></td>
      <td><?php echo $localidad_actividad->getLocalidadId() ?></td>
      <td><?php echo $localidad_actividad->getActividadId() ?></td>
      <td><?php echo $localidad_actividad->getMonto() ?></td>
      <td><?php echo $localidad_actividad->getCantidad() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'localidadact/create') ?>
