<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:21:47
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $localidad_actividad->getId() ?></td>
</tr>
<tr>
<th>Localidad: </th>
<td><?php echo $localidad_actividad->getLocalidadId() ?></td>
</tr>
<tr>
<th>Actividad: </th>
<td><?php echo $localidad_actividad->getActividadId() ?></td>
</tr>
<tr>
<th>Monto: </th>
<td><?php echo $localidad_actividad->getMonto() ?></td>
</tr>
<tr>
<th>Cantidad: </th>
<td><?php echo $localidad_actividad->getCantidad() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'localidadact/edit?id='.$localidad_actividad->getId()) ?>
&nbsp;<?php echo link_to('Listar', 'localidadact/list') ?>
