<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:11
?>
<?php

/**
 * fuenteactividad actions.
 *
 * @package    indicadores
 * @subpackage fuenteactividad
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class fuenteactividadActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('fuenteactividad', 'list');
  }

  public function executeList()
  {
    // listar las fuentes de la actividad seleccionada
    if($this->getRequestParameter('actividad')) {
      $c = new Criteria();
      $c->add(FuenteActividadPeer::ACTIVIDAD_ID, $this->getRequestParameter('actividad'));

      $this->fuente_actividads = FuenteActividadPeer::doSelect($c);

    // mostrar la lista de actividades correspondiente al proyecto y mes
    } elseif (($this->getRequestParameter('proyecto')) && ($this->getRequestParameter('mes'))) {
      $c = new Criteria();
      $c->add(ActividadPeer::PROYECTO_ID, $this->getRequestParameter('proyecto'));
      $c->add(ActividadPeer::MES_INICIO_EJECUCION, $this->getRequestParameter('mes'));

      $this->actividads = ActividadPeer::doSelect($c);

      $this->setTemplate('ListActividades');
    // mostrar formulario de busqueda de actividad
    } else {
      $this->setTemplate('BuscarActividad');

    }
  }

  public function executeShow()
  {
    $this->fuente_actividad = FuenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->fuente_actividad);
  }

  public function executeCreate()
  {
    if($this->getRequestParameter('actividad')) {
      $this->fuente_actividad = new FuenteActividad();
      $this->actividad = ActividadPeer::retrieveByPK($this->getRequestParameter('actividad'));

      $this->setTemplate('edit');

    } elseif (($this->getRequestParameter('proyecto')) && ($this->getRequestParameter('mes'))) {
      $c = new Criteria();
      $c->add(ActividadPeer::PROYECTO_ID, $this->getRequestParameter('proyecto'));
      $c->add(ActividadPeer::MES_INICIO_EJECUCION, $this->getRequestParameter('mes'));

      $this->actividads = ActividadPeer::doSelect($c);

      $this->setTemplate('ListActividadesCreate');
    // mostrar formulario de busqueda de actividad
    } else {
      $this->setTemplate('BuscarActividadCreate');

    }

  }

  public function executeEdit()
  {
    $this->fuente_actividad = FuenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->actividad = ActividadPeer::retrieveByPK($this->getRequestParameter('actividad'));
    $this->forward404Unless($this->fuente_actividad);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $fuente_actividad = new FuenteActividad();
    }
    else
    {
      $fuente_actividad = FuenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($fuente_actividad);
    }

    $fuente_actividad->setId($this->getRequestParameter('id'));
    $fuente_actividad->setFuenteId($this->getRequestParameter('fuente_id') ? $this->getRequestParameter('fuente_id') : null);
    $fuente_actividad->setActividadId($this->getRequestParameter('actividad_id') ? $this->getRequestParameter('actividad_id') : null);
    $fuente_actividad->setMonto($this->getRequestParameter('monto'));

    $fuente_actividad->save();

    return $this->redirect('fuenteactividad/show?id='.$fuente_actividad->getId());
  }

  public function executeDelete()
  {
    $fuente_actividad = FuenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($fuente_actividad);

    $fuente_actividad->delete();

    return $this->redirect('fuenteactividad/list');
  }
}
