<?php
// auto-generated by sfPropelCrud
// date: 2010/09/20 19:42:22
?>
<?php

/**
 * subactividadpoaejecucion actions.
 *
 * @package    indicadores
 * @subpackage subactividadpoaejecucion
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class subactividadpoaejecucionActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('subactividadpoaejecucion', 'list');
  }

  public function executeList()
  {
    $this->subactividad_poa_ejecucions = SubactividadPoaEjecucionPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->subactividad_poa_ejecucion = SubactividadPoaEjecucionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->subactividad_poa_ejecucion);
  }

  public function executeCreate()
  {
    $this->subactividad_poa_ejecucion = new SubactividadPoaEjecucion();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->subactividad_poa_ejecucion = SubactividadPoaEjecucionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->subactividad_poa_ejecucion);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $subactividad_poa_ejecucion = new SubactividadPoaEjecucion();
    }
    else
    {
      $subactividad_poa_ejecucion = SubactividadPoaEjecucionPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($subactividad_poa_ejecucion);
    }

    $subactividad_poa_ejecucion->setId($this->getRequestParameter('id'));
    $subactividad_poa_ejecucion->setSubactividadProyectoId($this->getRequestParameter('subactividad_proyecto_id') ? $this->getRequestParameter('subactividad_proyecto_id') : null);
    $subactividad_poa_ejecucion->setMes($this->getRequestParameter('mes'));
    $subactividad_poa_ejecucion->setDescripcion($this->getRequestParameter('descripcion'));
    $subactividad_poa_ejecucion->setAvance($this->getRequestParameter('avance'));

    $subactividad_poa_ejecucion->save();

    return $this->redirect('subactividadpoaejecucion/show?id='.$subactividad_poa_ejecucion->getId());
  }

  public function executeDelete()
  {
    $subactividad_poa_ejecucion = SubactividadPoaEjecucionPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($subactividad_poa_ejecucion);

    $subactividad_poa_ejecucion->delete();

    return $this->redirect('subactividadpoaejecucion/list');
  }
}
