<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 15:35:09
?>
<?php

/**
 * macroproceso actions.
 *
 * @package    indicadores
 * @subpackage macroproceso
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class macroprocesoActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('macroproceso', 'list');
  }

  public function executeList()
  {
    $this->macroprocesos = MacroprocesoPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->macroproceso = MacroprocesoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->macroproceso);
  }

  public function executeCreate()
  {
    $this->macroproceso = new Macroproceso();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->macroproceso = MacroprocesoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->macroproceso);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $macroproceso = new Macroproceso();
    }
    else
    {
      $macroproceso = MacroprocesoPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($macroproceso);
    }

    $macroproceso->setId($this->getRequestParameter('id'));
    $macroproceso->setNombre($this->getRequestParameter('nombre'));
    $macroproceso->setDescripcion($this->getRequestParameter('descripcion'));

    $macroproceso->save();

    return $this->redirect('macroproceso/show?id='.$macroproceso->getId());
  }

  public function executeDelete()
  {
    $macroproceso = MacroprocesoPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($macroproceso);

    $macroproceso->delete();

    return $this->redirect('macroproceso/list');
  }
}
