<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:15:00
?>
<?php

/**
 * indicadormeta actions.
 *
 * @package    indicadores
 * @subpackage indicadormeta
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class indicadormetaActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('indicadormeta', 'list');
  }

  public function executeList()
  {
    $this->indicador_metas = IndicadorMetaPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->indicador_meta = IndicadorMetaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->indicador_meta);
  }

  public function executeCreate()
  {
    $this->indicador_meta = new IndicadorMeta();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->indicador_meta = IndicadorMetaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->indicador_meta);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $indicador_meta = new IndicadorMeta();
    }
    else
    {
      $indicador_meta = IndicadorMetaPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($indicador_meta);
    }

    $indicador_meta->setId($this->getRequestParameter('id'));
    $indicador_meta->setMetaPdId($this->getRequestParameter('meta_pd_id') ? $this->getRequestParameter('meta_pd_id') : null);
    $indicador_meta->setCodigo($this->getRequestParameter('codigo'));
    $indicador_meta->setDescripcion($this->getRequestParameter('descripcion'));
    $indicador_meta->setMagnitud($this->getRequestParameter('magnitud'));
    $indicador_meta->setAnualizacionId($this->getRequestParameter('anualizacion_id') ? $this->getRequestParameter('anualizacion_id') : null);

    $indicador_meta->save();

    return $this->redirect('indicadormeta/show?id='.$indicador_meta->getId());
  }

  public function executeDelete()
  {
    $indicador_meta = IndicadorMetaPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($indicador_meta);

    $indicador_meta->delete();

    return $this->redirect('indicadormeta/list');
  }
}
