<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:13:50
?>
<?php use_helper('Object') ?>

<?php echo form_tag('metapd/update') ?>

<?php echo object_input_hidden_tag($meta_pd, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Codigo:</th>
  <td><?php echo object_input_tag($meta_pd, 'getCodigo', array (
  'size' => 30,
)) ?></td>
</tr>
<tr>
  <th>Meta:</th>
  <td><?php echo object_input_tag($meta_pd, 'getMeta', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($meta_pd, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Tipo:</th>
  <td><?php echo object_input_tag($meta_pd, 'getTipo', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($meta_pd->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'metapd/delete?id='.$meta_pd->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'metapd/show?id='.$meta_pd->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'metapd/list') ?>
<?php endif; ?>
</form>
