<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:13:50
?>
<h1>Metas Plan de Desarrollo</h1>

<table class="data">
<thead>
<tr>
  <th>Codigo</th>
  <th>Meta</th>
  <th>Descripcion</th>
  <th>Tipo</th>
</tr>
</thead>
<tbody>
<?php foreach ($meta_pds as $meta_pd): ?>
<tr>
    <td><?php echo link_to($meta_pd->getCodigo(), 'metapd/show?id='.$meta_pd->getId()) ?></td>
      <td><?php echo $meta_pd->getMeta() ?></td>
      <td><?php echo $meta_pd->getDescripcion() ?></td>
      <td><?php echo $meta_pd->getTipo() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
