<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 15:34:56
?>
<?php use_helper('Object') ?>

<?php echo form_tag('proceso/update') ?>

<?php echo object_input_hidden_tag($proceso, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Macroproceso:</th>
  <td><?php echo object_select_tag($proceso, 'getMacroprocesoId', array (
  'related_class' => 'Macroproceso',
  'include_blank' => false,
)) ?></td>
</tr>
<tr>
  <th>Nombre:</th>
  <td><?php echo object_input_tag($proceso, 'getNombre', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Cargo:</th>
  <td><?php echo object_select_tag($proceso, 'getCargoId', array (
  'related_class' => 'Cargo',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($proceso, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('Guardar','class="button"') ?>
<?php if ($proceso->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'proceso/delete?id='.$proceso->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'proceso/show?id='.$proceso->getId(), 'class="button"') ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'proceso/list', 'class="button') ?>
<?php endif; ?>
</form>
