<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 15:34:56
?>
<table class="data">
<tbody>
<tr>
<th>Macroproceso: </th>
<td><?php echo $proceso->getMacroproceso() ?></td>
</tr>
<tr>
<th>Nombre: </th>
<td><?php echo $proceso->getNombre() ?></td>
</tr>
<tr>
<th>Cargo: </th>
<td><?php echo $proceso->getCargo() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $proceso->getDescripcion() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'proceso/edit?id='.$proceso->getId(), 'class="button"') ?>
&nbsp;<?php echo link_to('Regresar a la lista', 'proceso/list', 'class="button"') ?>
