<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:13:41
?>
<?php use_helper('Object') ?>

<?php echo form_tag('cliente/update') ?>

<?php echo object_input_hidden_tag($cliente, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Cliente:</th>
  <td><?php echo object_input_tag($cliente, 'getCliente', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($cliente->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'cliente/delete?id='.$cliente->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'cliente/show?id='.$cliente->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'cliente/list') ?>
<?php endif; ?>
</form>
