<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:23:15
?>
<?php use_helper('Object') ?>

<?php echo form_tag('cliente/update') ?>

<?php echo object_input_hidden_tag($cliente, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Cliente:</th>
  <td><?php echo object_input_tag($cliente, 'getCliente', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($cliente->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'cliente/delete?id='.$cliente->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'cliente/show?id='.$cliente->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'cliente/list') ?>
<?php endif; ?>
</form>
