<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:23:15
?>
<h1>cliente</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Cliente</th>
</tr>
</thead>
<tbody>
<?php foreach ($clientes as $cliente): ?>
<tr>
    <td><?php echo link_to($cliente->getId(), 'cliente/show?id='.$cliente->getId()) ?></td>
      <td><?php echo $cliente->getCliente() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'cliente/create') ?>
