<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:13:41
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $cliente->getId() ?></td>
</tr>
<tr>
<th>Cliente: </th>
<td><?php echo $cliente->getCliente() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'cliente/edit?id='.$cliente->getId(), 'class="button"') ?>
&nbsp;<?php echo link_to('Listar', 'cliente/list') ?>
