<?php
// auto-generated by sfPropelCrud
// date: 2009/02/05 17:13:26
?>
<h1>seguimiento</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Variable</th>
  <th>Valor</th>
  <th>Historico indicador</th>
</tr>
</thead>
<tbody>
<?php foreach ($historico_variables as $i => $historico_variable): ?>
<tr class="<?php echo fmod($i, 2) ? 'par' : 'impar' ?>">
    <td><?php echo link_to($historico_variable->getId(), 'seguimiento/show?id='.$historico_variable->getId()) ?></td>
      <td><?php echo $historico_variable->getVariableId() ?></td>
      <td><?php echo $historico_variable->getValor() ?></td>
      <td><?php echo $historico_variable->getHistoricoIndicadorId() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'seguimiento/create') ?>
