<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:53
?>
<?php use_helper('Object') ?>

<?php echo form_tag('cdpactividad/update') ?>

<?php echo object_input_hidden_tag($cdp_actividad, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Cdp:</th>
  <td><?php echo object_select_tag($cdp_actividad, 'getCdpId', array (
  'related_class' => 'Cdp',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Actividad:</th>
  <td><?php echo object_select_tag($cdp_actividad, 'getActividadId', array (
  'related_class' => 'Actividad',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($cdp_actividad->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'cdpactividad/delete?id='.$cdp_actividad->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'cdpactividad/show?id='.$cdp_actividad->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'cdpactividad/list') ?>
<?php endif; ?>
</form>
