<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:53
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $cdp_actividad->getId() ?></td>
</tr>
<tr>
<th>Cdp: </th>
<td><?php echo $cdp_actividad->getCdpId() ?></td>
</tr>
<tr>
<th>Actividad: </th>
<td><?php echo $cdp_actividad->getActividadId() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'cdpactividad/edit?id='.$cdp_actividad->getId(), 'class="button"') ?>
&nbsp;<?php echo link_to('Listar', 'cdpactividad/list') ?>
