<?php
// auto-generated by sfPropelCrud
// date: 2009/02/04 17:13:23
?>
<?php

/**
 * indicadorvariable actions.
 *
 * @package    indicadores
 * @subpackage indicadorvariable
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class indicadorvariableActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('indicadorvariable', 'list');
  }

  public function executeList()
  {
    if (!$this->getRequestParameter('indicador'))
    {
      $this->indicadores = IndicadorPeer::doSelect(new Criteria());
      $this->setTemplate('listIndicadoresVariables');
    }
    else
    {
      $c = new Criteria();
      $c->add(IndicadorVariablePeer::INDICADOR_ID, $this->getRequestParameter('indicador'));
      $this->indicador_variables = IndicadorVariablePeer::doSelect($c);
      $this->setTemplate('list');
    }
    
  }

  public function executeShow()
  {
    $this->indicador_variable = IndicadorVariablePeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->indicador_variable);
  }

  public function executeCreate()
  {
    $this->indicador_variable = new IndicadorVariable();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->indicador_variable = IndicadorVariablePeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->indicador_variable);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $indicador_variable = new IndicadorVariable();
    }
    else
    {
      $indicador_variable = IndicadorVariablePeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($indicador_variable);
    }

    $indicador_variable->setId($this->getRequestParameter('id'));
    $indicador_variable->setIndicadorId($this->getRequestParameter('indicador_id') ? $this->getRequestParameter('indicador_id') : null);
    $indicador_variable->setVariableId($this->getRequestParameter('variable_id') ? $this->getRequestParameter('variable_id') : null);

    $indicador_variable->save();

    return $this->redirect('indicadorvariable/show?id='.$indicador_variable->getId());
  }

  public function executeDelete()
  {
    $indicador_variable = IndicadorVariablePeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($indicador_variable);

    $indicador_variable->delete();

    return $this->redirect('indicadorvariable/list');
  }
}
