<?php
// auto-generated by sfPropelCrud
// date: 2010/08/03 01:36:47
?>
<?php use_helper('Object') ?>
<?php use_helper('Javascript') ?>

<?php echo form_tag('subactividadproyecto/update') ?>

<?php echo object_input_hidden_tag($subactividad_proyecto, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Proyecto:</th>
  <td><?php echo select_tag('proyecto_id', objects_for_select($proyectos, 'getId', '__toString', '', 'include_blank=true')) ?>


  <?php
  echo observe_field('proyecto_id', array(
  'update'   => 'actividad_proyecto_id',
  'url'      => 'ajax/actividadporproyecto',
  'with'     => "'proyecto=' + value",
  'script'   => true,
  'loading' => "Element.show('indicator')",
  'complete' => "Element.hide('indicator')",
));
?>

  </td>
</tr>
<tr>
  <th>Actividad proyecto:</th>
  <td><?php echo object_select_tag($subactividad_proyecto, 'getActividadProyectoId', array (
  'related_class' => 'ActividadProyecto',
  'include_blank' => true,
)) ?>

  <?php
    echo observe_field('actividad_proyecto_id', array(
    'update'   => 'pond',
    'url'      => 'ajax/subactividad',
    'with'     => "'actividad=' + value",
    'script'   => true,
    ));
  ?>
  </td>
</tr>
<tr>
  <th>Descripcion*:</th>
  <td><?php echo object_textarea_tag($subactividad_proyecto, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Entregable*:</th>
  <td><?php echo object_textarea_tag($subactividad_proyecto, 'getEntregable', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Fecha inicio*:</th>
  <td><?php echo object_input_date_tag($subactividad_proyecto, 'getFechaInicio', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Duracion*:</th>
  <td><?php echo object_input_tag($subactividad_proyecto, 'getDuracion', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Ponderacion*:</th>
  <td><?php echo object_input_tag($subactividad_proyecto, 'getPonderacion', array (
  'size' => 7,)) ?>
    &nbsp;Ponderacion Acumulada <div id="pond" style="display: inline"></div>%</td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($subactividad_proyecto->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'subactividadproyecto/delete?id='.$subactividad_proyecto->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'subactividadproyecto/show?id='.$subactividad_proyecto->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'subactividadproyecto/list') ?>
<?php endif; ?>
</form>
