<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:16:28
?>
<h1>subactividadproyecto</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Actividad proyecto</th>
  <th>Descripcion</th>
  <th>Fecha inicio</th>
  <th>Duracion</th>
  <th>Ponderacion</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($subactividad_proyectos as $subactividad_proyecto): ?>
<tr>
    <td><?php echo link_to($subactividad_proyecto->getId(), 'subactividadproyecto/show?id='.$subactividad_proyecto->getId()) ?></td>
      <td><?php echo $subactividad_proyecto->getActividadProyecto() ?></td>
      <td><?php echo $subactividad_proyecto->getDescripcion() ?></td>
      <td><?php echo $subactividad_proyecto->getFechaInicio() ?></td>
      <td><?php echo $subactividad_proyecto->getDuracion() ?></td>
      <td><?php echo $subactividad_proyecto->getPonderacion() ?></td>
      <td><?php echo $subactividad_proyecto->getCreatedAt() ?></td>
      <td><?php echo $subactividad_proyecto->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'subactividadproyecto/create') ?>
