<?php
// auto-generated by sfPropelCrud
// date: 2010/08/03 01:36:47
?>
<h1>subactividadproyecto</h1>

<table class="data">
<thead>
<tr>
  <th>Actividad proyecto</th>
  <th>Descripcion</th>
  <th>Entregable</th>
  <th>Fecha inicio</th>
  <th>Duracion</th>
  <th>Ponderacion</th>
</tr>
</thead>
<tbody>
<?php foreach ($subactividad_proyectos as $subactividad_proyecto): ?>
<tr>
    <td><?php echo link_to($subactividad_proyecto->getActividadProyecto(), 'subactividadproyecto/edit?id='.$subactividad_proyecto->getId()) ?></td>
      <td><?php echo $subactividad_proyecto->getDescripcion() ?></td>
      <td><?php echo $subactividad_proyecto->getEntregable() ?></td>
      <td><?php echo $subactividad_proyecto->getFechaInicio() ?></td>
      <td><?php echo $subactividad_proyecto->getDuracion() ?></td>
      <td><?php echo $subactividad_proyecto->getPonderacion() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
