<?php
// auto-generated by sfPropelCrud
// date: 2010/08/27 15:42:00
?>
<?php

/**
 * seguimientometas actions.
 *
 * @package    indicadores
 * @subpackage seguimientometas
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class seguimientometasActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('seguimientometas', 'list');
  }

  public function executeList()
  {
    $this->seguimiento_indicador_metas = SeguimientoIndicadorMetaPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->seguimiento_indicador_meta = SeguimientoIndicadorMetaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->seguimiento_indicador_meta);
  }

  public function executeCreate()
  {
    $c = new Criteria();
    $c->add(AnualizacionPeer::META_PD_ID, $this->getRequestParameter('meta'));
    $meta = AnualizacionPeer::doSelectOne($c);

    $years = array();
    
    if ($meta->getAnyo1() != 0) { $years[1] = "Año 1"; }
    if ($meta->getAnyo2() != 0) { $years[2] = "Año 2"; }
    if ($meta->getAnyo3() != 0) { $years[3] = "Año 3"; }
    if ($meta->getAnyo4() != 0) { $years[4] = "Año 4"; }
    $this->years = $years;

    $this->seguimiento_indicador_meta = new SeguimientoIndicadorMeta();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $meta = MetaPdPeer::retrieveByPK($this->getRequestParameter('meta'));
    
    $years = array();
    
    if ($meta->getAnyo1() != 0) {
      $years[1] = "Año 1";
    } elseif ($meta->getAnyo2() != 0) {
      $years[2] = "Año 2";
    } elseif ($meta->getAnyo3() != 0) {
      $years[3] = "Año 3";
    } elseif ($meta->getAnyo4() != 0) {
      $years[4] = "Año 4";
    }

    $this->seguimiento_indicador_meta = SeguimientoIndicadorMetaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->seguimiento_indicador_meta);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $seguimiento_indicador_meta = new SeguimientoIndicadorMeta();
    }
    else
    {
      $seguimiento_indicador_meta = SeguimientoIndicadorMetaPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($seguimiento_indicador_meta);
    }

    $seguimiento_indicador_meta->setId($this->getRequestParameter('id'));
    $seguimiento_indicador_meta->setIndicadorMetaId($this->getRequestParameter('indicador_meta_id') ? $this->getRequestParameter('indicador_meta_id') : null);
    $seguimiento_indicador_meta->setAnyo($this->getRequestParameter('anyo'));
    $seguimiento_indicador_meta->setValor($this->getRequestParameter('valor'));

    $seguimiento_indicador_meta->save();

    return $this->redirect('seguimientometas/show?id='.$seguimiento_indicador_meta->getId());
  }

  public function executeDelete()
  {
    $seguimiento_indicador_meta = SeguimientoIndicadorMetaPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($seguimiento_indicador_meta);

    $seguimiento_indicador_meta->delete();

    return $this->redirect('seguimientometas/list');
  }
}
