<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:13:51
?>
<h1>clienteactividad</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Cliente</th>
  <th>Actividad</th>
  <th>Monto</th>
  <th>Cantidad</th>
</tr>
</thead>
<tbody>
<?php foreach ($cliente_actividads as $cliente_actividad): ?>
<tr>
    <td><?php echo link_to($cliente_actividad->getId(), 'clienteactividad/show?id='.$cliente_actividad->getId()) ?></td>
      <td><?php echo $cliente_actividad->getClienteId() ?></td>
      <td><?php echo $cliente_actividad->getActividadId() ?></td>
      <td><?php echo $cliente_actividad->getMonto() ?></td>
      <td><?php echo $cliente_actividad->getCantidad() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'clienteactividad/create') ?>
