<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:13:51
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $cliente_actividad->getId() ?></td>
</tr>
<tr>
<th>Cliente: </th>
<td><?php echo $cliente_actividad->getClienteId() ?></td>
</tr>
<tr>
<th>Actividad: </th>
<td><?php echo $cliente_actividad->getActividadId() ?></td>
</tr>
<tr>
<th>Monto: </th>
<td><?php echo $cliente_actividad->getMonto() ?></td>
</tr>
<tr>
<th>Cantidad: </th>
<td><?php echo $cliente_actividad->getCantidad() ?></td>
</tr>
</tbody>
</table>
<hr />
&nbsp;<?php echo link_to('list', 'clienteactividad/list') ?>
