<?php
// auto-generated by sfPropelAdmin
// date: 2010/07/19 22:02:20
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'sfGuardUser/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
