<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:25:29
?>
<?php use_helper('Object') ?>

<?php echo form_tag('contrato/update') ?>

<?php echo object_input_hidden_tag($contrato, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Numero:</th>
  <td><?php echo object_input_tag($contrato, 'getNumero', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Id contratista:</th>
  <td><?php echo object_input_tag($contrato, 'getIdContratista', array (
  'size' => 30,
)) ?></td>
</tr>
<tr>
  <th>Contratista:</th>
  <td><?php echo object_input_tag($contrato, 'getContratista', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($contrato->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'contrato/delete?id='.$contrato->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'contrato/show?id='.$contrato->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'contrato/list') ?>
<?php endif; ?>
</form>
