<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:15:30
?>
<h1>contrato</h1>

<table class="data">
<thead>
<tr>
  <th>Numero</th>
  <th>Contratista</th>
  <th>Fecha firma</th>
  <th>Fecha acta inicio</th>
  <th>Fecha terminacion</th>
  <th>Fecha liquidacion</th>
  <th>Modalidad contratacion</th>
  <th>Cantidad</th>
  <th>Unidad medida</th>
  <th>Clase contrato</th>
  <th>Plazo</th>
  <th>Estado</th>
</tr>
</thead>
<tbody>
<?php foreach ($contratos as $contrato): ?>
<tr>
    <td><?php echo link_to($contrato->getNumero(), 'contrato/show?id='.$contrato->getId()) ?></td>
      <td><?php echo $contrato->getContratista() ?></td>
      <td><?php echo $contrato->getFechaFirma() ?></td>
      <td><?php echo $contrato->getFechaActaInicio() ?></td>
      <td><?php echo $contrato->getFechaTerminacion() ?></td>
      <td><?php echo $contrato->getFechaLiquidacion() ?></td>
      <td><?php echo $contrato->getModalidadContratacion() ?></td>
      <td><?php echo $contrato->getCantidad() ?></td>
      <td><?php echo $contrato->getUnidadMedida() ?></td>
      <td><?php echo $contrato->getClaseContrato() ?></td>
      <td><?php echo $contrato->getPlazo() ?></td>
      <td><?php echo $contrato->getEstado() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'contrato/create') ?>
