<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:25:29
?>
<h1>contrato</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Numero</th>
  <th>Id contratista</th>
  <th>Contratista</th>
</tr>
</thead>
<tbody>
<?php foreach ($contratos as $contrato): ?>
<tr>
    <td><?php echo link_to($contrato->getId(), 'contrato/show?id='.$contrato->getId()) ?></td>
      <td><?php echo $contrato->getNumero() ?></td>
      <td><?php echo $contrato->getIdContratista() ?></td>
      <td><?php echo $contrato->getContratista() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'contrato/create') ?>
