<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:15:30
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $contrato->getId() ?></td>
</tr>
<tr>
<th>Numero: </th>
<td><?php echo $contrato->getNumero() ?></td>
</tr>
<tr>
<th>Contratista: </th>
<td><?php echo $contrato->getContratista() ?></td>
</tr>
<tr>
<th>Fecha firma: </th>
<td><?php echo $contrato->getFechaFirma() ?></td>
</tr>
<tr>
<th>Fecha acta inicio: </th>
<td><?php echo $contrato->getFechaActaInicio() ?></td>
</tr>
<tr>
<th>Fecha terminacion: </th>
<td><?php echo $contrato->getFechaTerminacion() ?></td>
</tr>
<tr>
<th>Fecha liquidacion: </th>
<td><?php echo $contrato->getFechaLiquidacion() ?></td>
</tr>
<tr>
<th>Modalidad contratacion: </th>
<td><?php echo $contrato->getModalidadContratacion() ?></td>
</tr>
<tr>
<th>Cantidad: </th>
<td><?php echo $contrato->getCantidad() ?></td>
</tr>
<tr>
<th>Unidad medida: </th>
<td><?php echo $contrato->getUnidadMedida() ?></td>
</tr>
<tr>
<th>Clase contrato: </th>
<td><?php echo $contrato->getClaseContrato() ?></td>
</tr>
<tr>
<th>Plazo: </th>
<td><?php echo $contrato->getPlazo() ?></td>
</tr>
<tr>
<th>Estado: </th>
<td><?php echo $contrato->getEstado() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'contrato/edit?id='.$contrato->getId()) ?>
&nbsp;<?php echo link_to('list', 'contrato/list') ?>
