<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:24:46
?>
<?php

/**
 * fuenteact actions.
 *
 * @package    indicadores
 * @subpackage fuenteact
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class fuenteactActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('fuenteact', 'list');
  }

  public function executeList()
  {
    $this->fuente_actividads = FuenteActividadPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->fuente_actividad = FuenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->fuente_actividad);
  }

  public function executeCreate()
  {
    $this->fuente_actividad = new FuenteActividad();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->fuente_actividad = FuenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->fuente_actividad);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $fuente_actividad = new FuenteActividad();
    }
    else
    {
      $fuente_actividad = FuenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($fuente_actividad);
    }

    $fuente_actividad->setId($this->getRequestParameter('id'));
    $fuente_actividad->setFuenteId($this->getRequestParameter('fuente_id') ? $this->getRequestParameter('fuente_id') : null);
    $fuente_actividad->setActividadId($this->getRequestParameter('actividad_id') ? $this->getRequestParameter('actividad_id') : null);
    $fuente_actividad->setMonto($this->getRequestParameter('monto'));

    $fuente_actividad->save();

    return $this->redirect('fuenteact/show?id='.$fuente_actividad->getId());
  }

  public function executeDelete()
  {
    $fuente_actividad = FuenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($fuente_actividad);

    $fuente_actividad->delete();

    return $this->redirect('fuenteact/list');
  }
}
