<?php
// auto-generated by sfPropelCrud
// date: 2010/07/15 21:17:09
?>
<?php use_helper('Object') ?>

<?php echo form_tag('proyecto/update') ?>

<?php echo object_input_hidden_tag($proyecto, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Codigo:</th>
  <td><?php echo object_input_tag($proyecto, 'getCodigo', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Proyecto:</th>
  <td><?php echo object_input_tag($proyecto, 'getProyecto', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($proyecto, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Magnitud:</th>
  <td><?php echo object_input_tag($proyecto, 'getMagnitud', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Programa interno:</th>
  <td><?php echo object_input_tag($proyecto, 'getProgramaInterno', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($proyecto->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'proyecto/delete?id='.$proyecto->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'proyecto/show?id='.$proyecto->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'proyecto/list') ?>
<?php endif; ?>
</form>
