<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:15:40
?>
<?php use_helper('Object') ?>

<?php echo form_tag('proyecto/update') ?>

<?php echo object_input_hidden_tag($proyecto, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Meta proyecto:</th>
  <td><?php echo object_select_tag($proyecto, 'getMetaProyectoId', array (
  'related_class' => 'MetaProyecto',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Anualizacion:</th>
  <td><?php echo object_select_tag($proyecto, 'getAnualizacionId', array (
  'related_class' => 'Anualizacion',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Codigo:</th>
  <td><?php echo object_input_tag($proyecto, 'getCodigo', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Proyecto:</th>
  <td><?php echo object_input_tag($proyecto, 'getProyecto', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($proyecto, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Magnitud:</th>
  <td><?php echo object_input_tag($proyecto, 'getMagnitud', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Programa interno:</th>
  <td><?php echo object_input_tag($proyecto, 'getProgramaInterno', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($proyecto->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'proyecto/delete?id='.$proyecto->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'proyecto/show?id='.$proyecto->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'proyecto/list') ?>
<?php endif; ?>
</form>
