<?php
// auto-generated by sfPropelCrud
// date: 2009/02/05 17:13:26
?>
<?php

/**
 * seguimiento actions.
 *
 * @package    indicadores
 * @subpackage seguimiento
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class seguimientoActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('seguimiento', 'list');
  }

  public function executeList()
  {
    if ($this->getRequestParameter('objetivo'))
    {
      // listar los indicadores relacionados con el objetivo
      $c = new Criteria();
      $c->add(IndicadorPeer::OBJETIVO_ID, $this->getRequestParameter('objetivo'));
      $this->indicadors = IndicadorPeer::doSelect($c);
      $this->setTemplate('listIndicadores');
    }
    elseif($this->getRequestParameter('indicador'))
    {
      $c = new Criteria();
      $c->add(IndicadorVariablePeer::INDICADOR_ID, $this->getRequestParameter('indicador'));
      $this->indicador_variables = IndicadorVariablePeer::doSelect($c);
      $this->setTemplate('list');
    } else {
      $this->objetivos = ObjetivoPeer::doSelect(new Criteria());
      $this->setTemplate('listObjetivos');
    }
  }

  public function executeShow()
  {
    $this->historico_variable = HistoricoVariablePeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->historico_variable);
  }

  public function executeCreate()
  {
    $this->historico_variable = new HistoricoVariable();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->historico_variable = HistoricoVariablePeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->historico_variable);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $historico_variable = new HistoricoVariable();
    }
    else
    {
      $historico_variable = HistoricoVariablePeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($historico_variable);
    }

    $historico_variable->setId($this->getRequestParameter('id'));
    $historico_variable->setVariableId($this->getRequestParameter('variable_id') ? $this->getRequestParameter('variable_id') : null);
    $historico_variable->setValor($this->getRequestParameter('valor'));
    $historico_variable->setHistoricoIndicadorId($this->getRequestParameter('historico_indicador_id') ? $this->getRequestParameter('historico_indicador_id') : null);

    $historico_variable->save();

    return $this->redirect('seguimiento/show?id='.$historico_variable->getId());
  }

  public function executeDelete()
  {
    $historico_variable = HistoricoVariablePeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($historico_variable);

    $historico_variable->delete();

    return $this->redirect('seguimiento/list');
  }
}
