<?php
// auto-generated by sfPropelCrud
// date: 2010/08/03 04:03:47
?>
<?php use_helper('Object') ?>
<?php use_helper('Javascript') ?>

<?php echo form_tag('actividadproyecto/update') ?>

<?php echo object_input_hidden_tag($actividad_proyecto, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Proyecto:</th>
  <td><?php echo object_select_tag($actividad_proyecto, 'getProyectoId', array (
  'related_class' => 'Proyecto',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Meta pd:</th>
  <td><?php echo object_select_tag($actividad_proyecto, 'getMetaPdId', array (
  'related_class' => 'MetaPd',
  'include_blank' => true,
)) ?>
  <?php
  echo observe_field('meta_pd_id', array(
  'update'   => 'pond',
  'url'      => 'ajax/actividad',
  'with'     => "'meta=' + value",
  'script'   => true,
));
?>
  </td>
</tr>
<tr>
  <th>Meta proyecto:</th>
  <td><?php echo object_select_tag($actividad_proyecto, 'getMetaProyectoId', array (
  'related_class' => 'MetaProyecto',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Actividad*:</th>
  <td><?php echo object_input_tag($actividad_proyecto, 'getActividad', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($actividad_proyecto, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Ponderacion*:</th>
  <td><?php echo object_input_tag($actividad_proyecto, 'getPonderacion', array (
  'size' => 2,
)) ?>
    &nbsp;Ponderacion Acumulada <div id="pond" style="display: inline"></div>%</td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($actividad_proyecto->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'actividadproyecto/delete?id='.$actividad_proyecto->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'actividadproyecto/show?id='.$actividad_proyecto->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'actividadproyecto/list') ?>
<?php endif; ?>
</form>
