<?php
// auto-generated by sfPropelCrud
// date: 2010/08/03 04:03:47
?>
<h1>actividadproyecto</h1>

<table class="data">
<thead>
<tr>
  <th>Id</th>
  <th>Proyecto</th>
  <th>Meta pd</th>
  <th>Meta proyecto</th>
  <th>Actividad</th>
  <th>Descripcion</th>
  <th>Ponderacion</th>

</tr>
</thead>
<tbody>
<?php foreach ($actividad_proyectos as $actividad_proyecto): ?>
<tr>
    <td><?php echo link_to($actividad_proyecto->getId(), 'actividadproyecto/show?id='.$actividad_proyecto->getId()) ?></td>
      <td><?php echo $actividad_proyecto->getProyectoId() ?></td>
      <td><?php echo $actividad_proyecto->getMetaPdId() ?></td>
      <td><?php echo $actividad_proyecto->getMetaProyectoId() ?></td>
      <td><?php echo $actividad_proyecto->getActividad() ?></td>
      <td><?php echo $actividad_proyecto->getDescripcion() ?></td>
      <td><?php echo $actividad_proyecto->getPonderacion() ?></td>

  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'actividadproyecto/create') ?>
