<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 16:39:51
?>
<?php

/**
 * dependencia actions.
 *
 * @package    indicadores
 * @subpackage dependencia
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class dependenciaActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('dependencia', 'list');
  }

  public function executeList()
  {
    $this->dependencias = DependenciaPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->dependencia = DependenciaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->dependencia);
  }

  public function executeCreate()
  {
    $this->dependencia = new Dependencia();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->dependencia = DependenciaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->dependencia);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $dependencia = new Dependencia();
    }
    else
    {
      $dependencia = DependenciaPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($dependencia);
    }

    $dependencia->setId($this->getRequestParameter('id'));
    $dependencia->setNombre($this->getRequestParameter('nombre'));

    $dependencia->save();

    return $this->redirect('dependencia/show?id='.$dependencia->getId());
  }

  public function executeDelete()
  {
    $dependencia = DependenciaPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($dependencia);

    $dependencia->delete();

    return $this->redirect('dependencia/list');
  }
}
