<?php
// auto-generated by sfPropelCrud
// date: 2010/09/16 23:20:05
?>
<h1>procedimiento</h1>

<table class="data">
<thead>
<tr>
  <th>Id</th>
  <th>Proceso</th>
  <th>Nombre</th>
  <th>Descripcion</th>
</tr>
</thead>
<tbody>
<?php foreach ($procedimientos as $procedimiento): ?>
<tr>
    <td><?php echo link_to($procedimiento->getId(), 'procedimiento/show?id='.$procedimiento->getId()) ?></td>
      <td><?php echo $procedimiento->getProcesoId() ?></td>
      <td><?php echo $procedimiento->getNombre() ?></td>
      <td><?php echo $procedimiento->getDescripcion() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'procedimiento/create') ?>
