<?php
// auto-generated by sfPropelCrud
// date: 2010/09/16 23:20:05
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $procedimiento->getId() ?></td>
</tr>
<tr>
<th>Proceso: </th>
<td><?php echo $procedimiento->getProcesoId() ?></td>
</tr>
<tr>
<th>Nombre: </th>
<td><?php echo $procedimiento->getNombre() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $procedimiento->getDescripcion() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'procedimiento/edit?id='.$procedimiento->getId()) ?>
&nbsp;<?php echo link_to('list', 'procedimiento/list') ?>
