<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:24:59
?>
<?php use_helper('Object') ?>

<?php echo form_tag('componente/update') ?>

<?php echo object_input_hidden_tag($componente, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Codigo:</th>
  <td><?php echo object_input_tag($componente, 'getCodigo', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Componente:</th>
  <td><?php echo object_input_tag($componente, 'getComponente', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($componente->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'componente/delete?id='.$componente->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'componente/show?id='.$componente->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'componente/list') ?>
<?php endif; ?>
</form>
