<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:24:59
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $componente->getId() ?></td>
</tr>
<tr>
<th>Codigo: </th>
<td><?php echo $componente->getCodigo() ?></td>
</tr>
<tr>
<th>Componente: </th>
<td><?php echo $componente->getComponente() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'componente/edit?id='.$componente->getId()) ?>
&nbsp;<?php echo link_to('list', 'componente/list') ?>
