<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:27
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $componente->getId() ?></td>
</tr>
<tr>
<th>Codigo: </th>
<td><?php echo $componente->getCodigo() ?></td>
</tr>
<tr>
<th>Componente: </th>
<td><?php echo $componente->getComponente() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'componente/edit?id='.$componente->getId()) ?>
&nbsp;<?php echo link_to('Listar', 'componente/list') ?>
