<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:15:00
?>
<?php use_helper('Object') ?>

<?php echo form_tag('indicadormeta/update') ?>

<?php echo object_input_hidden_tag($indicador_meta, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Meta pd:</th>
  <td><?php echo object_select_tag($indicador_meta, 'getMetaPdId', array (
  'related_class' => 'MetaPd',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Codigo:</th>
  <td><?php echo object_input_tag($indicador_meta, 'getCodigo', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($indicador_meta, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Magnitud:</th>
  <td><?php echo object_input_tag($indicador_meta, 'getMagnitud', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Anualizacion:</th>
  <td><?php echo object_select_tag($indicador_meta, 'getAnualizacionId', array (
  'related_class' => 'Anualizacion',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($indicador_meta->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'indicadormeta/delete?id='.$indicador_meta->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'indicadormeta/show?id='.$indicador_meta->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'indicadormeta/list') ?>
<?php endif; ?>
</form>
