<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:15:00
?>
<h1>Indicador Meta Plan Desarrollo</h1>

<table class="data">
<thead>
<tr>
  <th>Codigo</th>
  <th>Meta Plan Desarrollo</th>
  <th>Descripcion</th>
  <th>Magnitud</th>
  <th>Anualizacion</th>
</tr>
</thead>
<tbody>
<?php foreach ($indicador_metas as $indicador_meta): ?>
<tr>
    <td><?php echo link_to($indicador_meta->getCodigo(), 'indicadormeta/show?id='.$indicador_meta->getId()) ?></td>
      <td><?php echo $indicador_meta->getMetaPd() ?></td>
      <td><?php echo $indicador_meta->getDescripcion() ?></td>
      <td><?php echo $indicador_meta->getMagnitud() ?></td>
      <td><?php echo $indicador_meta->getAnualizacionId() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
