<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:15:00
?>
<h1>indicadormeta</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Meta pd</th>
  <th>Codigo</th>
  <th>Descripcion</th>
  <th>Magnitud</th>
  <th>Anualizacion</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($indicador_metas as $indicador_meta): ?>
<tr>
    <td><?php echo link_to($indicador_meta->getId(), 'indicadormeta/show?id='.$indicador_meta->getId()) ?></td>
      <td><?php echo $indicador_meta->getMetaPdId() ?></td>
      <td><?php echo $indicador_meta->getCodigo() ?></td>
      <td><?php echo $indicador_meta->getDescripcion() ?></td>
      <td><?php echo $indicador_meta->getMagnitud() ?></td>
      <td><?php echo $indicador_meta->getAnualizacionId() ?></td>
      <td><?php echo $indicador_meta->getCreatedAt() ?></td>
      <td><?php echo $indicador_meta->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'indicadormeta/create') ?>
