<?php
// auto-generated by sfPropelCrud
// date: 2009/02/04 17:12:45
?>
<table class="data">
<tbody>
<tr>
<th>Nombre: </th>
<td><?php echo $objetivo->getNombre() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $objetivo->getDescripcion() ?></td>
</tr>
<tr>
<th>Nombre corto: </th>
<td><?php echo $objetivo->getNombreCorto() ?></td>
</tr>
<tr>
<th>Tema: </th>
<td><?php echo $objetivo->getTema() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $objetivo->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $objetivo->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />

<?php echo link_to('Editar', 'objetivo/edit?id='.$objetivo->getId(), 'class="button"') ?>
&nbsp;<?php echo link_to('Regresar a la lista', 'objetivo/list', 'class="button"') ?>
