<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:25:29
?>
<?php

/**
 * contrato actions.
 *
 * @package    indicadores
 * @subpackage contrato
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class contratoActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('contrato', 'list');
  }

  public function executeList()
  {
    $this->contratos = ContratoPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->contrato = ContratoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->contrato);
  }

  public function executeCreate()
  {
    $this->contrato = new Contrato();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->contrato = ContratoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->contrato);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $contrato = new Contrato();
    }
    else
    {
      $contrato = ContratoPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($contrato);
    }

    $contrato->setId($this->getRequestParameter('id'));
    $contrato->setNumero($this->getRequestParameter('numero'));
    $contrato->setIdContratista($this->getRequestParameter('id_contratista'));
    $contrato->setContratista($this->getRequestParameter('contratista'));

    $contrato->save();

    return $this->redirect('contrato/show?id='.$contrato->getId());
  }

  public function executeDelete()
  {
    $contrato = ContratoPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($contrato);

    $contrato->delete();

    return $this->redirect('contrato/list');
  }
}
