<?php
// auto-generated by sfPropelCrud
// date: 2009/02/04 17:12:45
?>
<?php

/**
 * objetivo actions.
 *
 * @package    indicadores
 * @subpackage objetivo
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class objetivoActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('objetivo', 'list');
  }

  public function executeList()
  {
    $this->objetivos = ObjetivoPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->objetivo = ObjetivoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->objetivo);
  }

  public function executeCreate()
  {
    $this->objetivo = new Objetivo();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->objetivo = ObjetivoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->objetivo);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $objetivo = new Objetivo();
    }
    else
    {
      $objetivo = ObjetivoPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($objetivo);
    }

    $objetivo->setId($this->getRequestParameter('id'));
    $objetivo->setNombre($this->getRequestParameter('nombre'));
    $objetivo->setDescripcion($this->getRequestParameter('descripcion'));
    $objetivo->setNombreCorto($this->getRequestParameter('nombre_corto'));
    $objetivo->setTema($this->getRequestParameter('tema'));

    $objetivo->save();

    return $this->redirect('objetivo/show?id='.$objetivo->getId());
  }

  public function executeDelete()
  {
    $objetivo = ObjetivoPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($objetivo);

    $objetivo->delete();

    return $this->redirect('objetivo/list');
  }
}
