<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:24:22
?>
<?php use_helper('Object') ?>

<?php echo form_tag('procedimientopoa/update') ?>

<?php echo object_input_hidden_tag($procedimiento_poa, 'getId') ?>

<table class="data">
<tbody>
<tr>
  <th>Procedimiento:</th>
  <td><?php echo object_select_tag($procedimiento_poa, 'getProcedimientoId', array (
  'related_class' => 'Procedimiento',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Ponderacion*:</th>
  <td><?php echo object_input_tag($procedimiento_poa, 'getPonderacion', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($procedimiento_poa->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'procedimientopoa/delete?id='.$procedimiento_poa->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'procedimientopoa/show?id='.$procedimiento_poa->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'procedimientopoa/list') ?>
<?php endif; ?>
</form>
