<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:24:22
?>
<h1>Programacion de Procedimientos POA</h1>

<table class="data">
<thead>
<tr>
  <th>Procedimiento</th>
  <th>Proceso</th>
  <th>Ponderacion</th>
</tr>
</thead>
<tbody>
<?php foreach ($procedimiento_poas as $procedimiento_poa): ?>
<tr>
    <td><?php echo link_to($procedimiento_poa->getProcedimiento(), 'procedimientopoa/show?id='.$procedimiento_poa->getId()) ?></td>
    <td><?php echo $procedimiento_poa->getProceso() ?>
    <td><?php echo $procedimiento_poa->getPonderacion() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>