<?php
// auto-generated by sfPropelCrud
// date: 2010/09/20 23:38:52
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $procedimiento_poa->getId() ?></td>
</tr>
<tr>
<th>Proceso: </th>
<td><?php echo $procedimiento_poa->getProcesoId() ?></td>
</tr>
<tr>
<th>Procedimiento: </th>
<td><?php echo $procedimiento_poa->getProcedimientoId() ?></td>
</tr>
<tr>
<th>Ponderacion: </th>
<td><?php echo $procedimiento_poa->getPonderacion() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'procedimientopoa/edit?id='.$procedimiento_poa->getId()) ?>
&nbsp;<?php echo link_to('list', 'procedimientopoa/list') ?>
