<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:24:22
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $procedimiento_poa->getId() ?></td>
</tr>
<tr>
<th>Procedimiento: </th>
<td><?php echo $procedimiento_poa->getProcedimientoId() ?></td>
</tr>
<tr>
<th>Ponderacion: </th>
<td><?php echo $procedimiento_poa->getPonderacion() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $procedimiento_poa->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $procedimiento_poa->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'procedimientopoa/edit?id='.$procedimiento_poa->getId()) ?>
&nbsp;<?php echo link_to('list', 'procedimientopoa/list') ?>
