<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:13:25
?>
<?php use_helper('Object') ?>

<?php echo form_tag('localidadactividad/update') ?>

<?php echo object_input_hidden_tag($localidad_actividad, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Localidad:</th>
  <td><?php echo object_select_tag($localidad_actividad, 'getLocalidadId', array (
  'related_class' => 'Localidad',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Actividad:</th>
  <td><?php echo object_select_tag($localidad_actividad, 'getActividadId', array (
  'related_class' => 'Actividad',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Monto:</th>
  <td><?php echo object_input_tag($localidad_actividad, 'getMonto', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Cantidad:</th>
  <td><?php echo object_input_tag($localidad_actividad, 'getCantidad', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($localidad_actividad->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'localidadactividad/delete?id='.$localidad_actividad->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'localidadactividad/show?id='.$localidad_actividad->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'localidadactividad/list') ?>
<?php endif; ?>
</form>
