<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:13:25
?>
<h1>localidadactividad</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Localidad</th>
  <th>Actividad</th>
  <th>Monto</th>
  <th>Cantidad</th>
</tr>
</thead>
<tbody>
<?php foreach ($localidad_actividads as $localidad_actividad): ?>
<tr>
    <td><?php echo link_to($localidad_actividad->getId(), 'localidadactividad/show?id='.$localidad_actividad->getId()) ?></td>
      <td><?php echo $localidad_actividad->getLocalidadId() ?></td>
      <td><?php echo $localidad_actividad->getActividadId() ?></td>
      <td><?php echo $localidad_actividad->getMonto() ?></td>
      <td><?php echo $localidad_actividad->getCantidad() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'localidadactividad/create') ?>
