<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:13:25
?>
<h1>localidadactividad</h1>

<table class="data">
<thead>
<tr>
  <th>Id</th>
  <th>Localidad</th>
  <th>Actividad</th>
  <th>Monto</th>
  <th>Cantidad</th>
</tr>
</thead>
<tbody>
<?php foreach ($localidad_actividads as $localidad_actividad): ?>
<tr>
    <td><?php echo link_to($localidad_actividad->getId(), 'localidadactividad/edit?id='.$localidad_actividad->getId().'&actividad='.$localidad_actividad->getActividadId()) ?></td>
      <td><?php echo $localidad_actividad->getLocalidad() ?></td>
      <td><?php echo $localidad_actividad->getActividad()->getDescripcion() ?></td>
      <td><?php echo $localidad_actividad->getMonto() ?></td>
      <td><?php echo $localidad_actividad->getCantidad() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
