<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:13:25
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $localidad_actividad->getId() ?></td>
</tr>
<tr>
<th>Localidad: </th>
<td><?php echo $localidad_actividad->getLocalidadId() ?></td>
</tr>
<tr>
<th>Actividad: </th>
<td><?php echo $localidad_actividad->getActividadId() ?></td>
</tr>
<tr>
<th>Monto: </th>
<td><?php echo $localidad_actividad->getMonto() ?></td>
</tr>
<tr>
<th>Cantidad: </th>
<td><?php echo $localidad_actividad->getCantidad() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'localidadactividad/edit?id='.$localidad_actividad->getId()) ?>
&nbsp;<?php echo link_to('list', 'localidadactividad/list') ?>
