<?php
// auto-generated by sfPropelCrud
// date: 2010/09/20 23:38:52
?>
<?php

/**
 * procedimientopoa actions.
 *
 * @package    indicadores
 * @subpackage procedimientopoa
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class procedimientopoaActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('procedimientopoa', 'list');
  }

  public function executeList()
  {
    $this->procedimiento_poas = ProcedimientoPoaPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->procedimiento_poa = ProcedimientoPoaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->procedimiento_poa);
  }

  public function executeCreate()
  {
    $this->procedimiento_poa = new ProcedimientoPoa();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->procedimiento_poa = ProcedimientoPoaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->procedimiento_poa);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $procedimiento_poa = new ProcedimientoPoa();
    }
    else
    {
      $procedimiento_poa = ProcedimientoPoaPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($procedimiento_poa);
    }

    $procedimiento_poa->setId($this->getRequestParameter('id'));
    $procedimiento_poa->setProcesoId($this->getRequestParameter('proceso_id') ? $this->getRequestParameter('proceso_id') : null);
    $procedimiento_poa->setProcedimientoId($this->getRequestParameter('procedimiento_id') ? $this->getRequestParameter('procedimiento_id') : null);
    $procedimiento_poa->setPonderacion($this->getRequestParameter('ponderacion'));

    $procedimiento_poa->save();

    return $this->redirect('procedimientopoa/show?id='.$procedimiento_poa->getId());
  }

  public function executeDelete()
  {
    $procedimiento_poa = ProcedimientoPoaPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($procedimiento_poa);

    $procedimiento_poa->delete();

    return $this->redirect('procedimientopoa/list');
  }
}
