<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:24:27
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $cliente_actividad->getId() ?></td>
</tr>
<tr>
<th>Cliente: </th>
<td><?php echo $cliente_actividad->getClienteId() ?></td>
</tr>
<tr>
<th>Actividad: </th>
<td><?php echo $cliente_actividad->getActividadId() ?></td>
</tr>
<tr>
<th>Monto: </th>
<td><?php echo $cliente_actividad->getMonto() ?></td>
</tr>
<tr>
<th>Cantidad: </th>
<td><?php echo $cliente_actividad->getCantidad() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'clienteact/edit?id='.$cliente_actividad->getId(), 'class="button"') ?>
&nbsp;<?php echo link_to('Listar', 'clienteact/list') ?>
