<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:16:14
?>
<h1>conceptogasto</h1>

<table class="data">
<thead>
<tr>
  <th>Id</th>
  <th>Concepto gasto</th>
</tr>
</thead>
<tbody>
<?php foreach ($concepto_gastos as $concepto_gasto): ?>
<tr>
    <td><?php echo link_to($concepto_gasto->getId(), 'conceptogasto/show?id='.$concepto_gasto->getId()) ?></td>
      <td><?php echo $concepto_gasto->getConceptoGasto() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'conceptogasto/create') ?>
