<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:16:14
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $concepto_gasto->getId() ?></td>
</tr>
<tr>
<th>Concepto gasto: </th>
<td><?php echo $concepto_gasto->getConceptoGasto() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'conceptogasto/edit?id='.$concepto_gasto->getId()) ?>
&nbsp;<?php echo link_to('list', 'conceptogasto/list') ?>
