<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 16:39:51
?>
<?php use_helper('Object') ?>

<?php echo form_tag('dependencia/update') ?>

<?php echo object_input_hidden_tag($dependencia, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Nombre:</th>
  <td><?php echo object_input_tag($dependencia, 'getNombre', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($dependencia->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'dependencia/delete?id='.$dependencia->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'dependencia/show?id='.$dependencia->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'dependencia/list') ?>
<?php endif; ?>
</form>
