<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 16:39:51
?>
<?php use_helper('Object') ?>

<?php echo form_tag('dependencia/update') ?>

<?php echo object_input_hidden_tag($dependencia, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Nombre:</th>
  <td><?php echo object_input_tag($dependencia, 'getNombre', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($dependencia->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'dependencia/delete?id='.$dependencia->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'dependencia/show?id='.$dependencia->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'dependencia/list') ?>
<?php endif; ?>
</form>
