<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 16:39:51
?>
<h1>dependencia</h1>

<table class="data">
<thead>
<tr>
  <th>Id</th>
  <th>Nombre</th>
</tr>
</thead>
<tbody>
<?php foreach ($dependencias as $dependencia): ?>
<tr>
    <td><?php echo link_to($dependencia->getId(), 'dependencia/show?id='.$dependencia->getId()) ?></td>
      <td><?php echo $dependencia->getNombre() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'dependencia/create') ?>
