<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 16:39:51
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $dependencia->getId() ?></td>
</tr>
<tr>
<th>Nombre: </th>
<td><?php echo $dependencia->getNombre() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'dependencia/edit?id='.$dependencia->getId()) ?>
&nbsp;<?php echo link_to('list', 'dependencia/list') ?>
