<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:22:36
?>
<?php

/**
 * cdpact actions.
 *
 * @package    indicadores
 * @subpackage cdpact
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class cdpactActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('cdpact', 'list');
  }

  public function executeList()
  {
    $this->cdp_actividads = CdpActividadPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->cdp_actividad = CdpActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->cdp_actividad);
  }

  public function executeCreate()
  {
    $this->cdp_actividad = new CdpActividad();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->cdp_actividad = CdpActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->cdp_actividad);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $cdp_actividad = new CdpActividad();
    }
    else
    {
      $cdp_actividad = CdpActividadPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($cdp_actividad);
    }

    $cdp_actividad->setId($this->getRequestParameter('id'));
    $cdp_actividad->setCdpId($this->getRequestParameter('cdp_id') ? $this->getRequestParameter('cdp_id') : null);
    $cdp_actividad->setActividadId($this->getRequestParameter('actividad_id') ? $this->getRequestParameter('actividad_id') : null);

    $cdp_actividad->save();

    return $this->redirect('cdpact/show?id='.$cdp_actividad->getId());
  }

  public function executeDelete()
  {
    $cdp_actividad = CdpActividadPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($cdp_actividad);

    $cdp_actividad->delete();

    return $this->redirect('cdpact/list');
  }
}
