<?php
// auto-generated by sfPropelCrud
// date: 2010/07/02 08:43:10
?>
<?php use_helper('Object') ?>

<?php echo form_tag('seguimientoindicador/update') ?>

<?php echo object_input_hidden_tag($seguimiento_indicador_meta, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Indicador meta:</th>
  <td><?php echo object_select_tag($seguimiento_indicador_meta, 'getIndicadorMetaId', array (
  'related_class' => 'IndicadorMeta',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Anyo:</th>
  <td><?php echo select_tag('anyo', options_for_select(array(1 =>1, 2 => 2, 3 =>3, 4 => 4), 0))?>
      <?php //echo object_select_tag($seguimiento_indicador_meta, 'getAnyo' )?>
        <?php //echo object_input_tag($seguimiento_indicador_meta, 'getAnyo', array ('size' => 20,)) ?></td>
</tr>
<tr>
  <th>Valor:</th>
  <td><?php echo object_input_tag($seguimiento_indicador_meta, 'getValor', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($seguimiento_indicador_meta->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'seguimientoindicador/delete?id='.$seguimiento_indicador_meta->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'seguimientoindicador/show?id='.$seguimiento_indicador_meta->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'seguimientoindicador/list') ?>
<?php endif; ?>
</form>
