<?php
// auto-generated by sfPropelCrud
// date: 2010/07/02 08:43:10
?>
<h1>seguimientoindicador</h1>

<table>
<thead>
<tr>
  <th>Meta</th>
  <th>Indicador meta</th>
  <th>Año</th>
  <th>Valor</th>
</tr>
</thead>
<tbody>
<?php foreach ($seguimiento_indicador_metas as $seguimiento_indicador_meta): ?>
<tr>
    <td><?php echo link_to($seguimiento_indicador_meta->getId(), 'seguimientoindicador/show?id='.$seguimiento_indicador_meta->getId()) ?></td>
      <td><?php echo $seguimiento_indicador_meta->getIndicadorMetaId() ?></td>
      <td><?php echo $seguimiento_indicador_meta->getAnyo() ?></td>
      <td><?php echo $seguimiento_indicador_meta->getValor() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'seguimientoindicador/create') ?>
