<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:25:11
?>
<h1>componenteact</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Componente</th>
  <th>Actividad</th>
  <th>Monto</th>
</tr>
</thead>
<tbody>
<?php foreach ($componente_actividads as $componente_actividad): ?>
<tr>
    <td><?php echo link_to($componente_actividad->getId(), 'componenteact/show?id='.$componente_actividad->getId()) ?></td>
      <td><?php echo $componente_actividad->getComponenteId() ?></td>
      <td><?php echo $componente_actividad->getActividadId() ?></td>
      <td><?php echo $componente_actividad->getMonto() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'componenteact/create') ?>
