<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:25:11
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $componente_actividad->getId() ?></td>
</tr>
<tr>
<th>Componente: </th>
<td><?php echo $componente_actividad->getComponenteId() ?></td>
</tr>
<tr>
<th>Actividad: </th>
<td><?php echo $componente_actividad->getActividadId() ?></td>
</tr>
<tr>
<th>Monto: </th>
<td><?php echo $componente_actividad->getMonto() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'componenteact/edit?id='.$componente_actividad->getId()) ?>
&nbsp;<?php echo link_to('list', 'componenteact/list') ?>
