<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:20:00
?>
<h1>actividadpoa</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Meta poa</th>
  <th>Proyecto</th>
  <th>Descripcion</th>
  <th>Responsable</th>
  <th>Observaciones</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($actividad_poas as $actividad_poa): ?>
<tr>
    <td><?php echo link_to($actividad_poa->getId(), 'actividadpoa/show?id='.$actividad_poa->getId()) ?></td>
      <td><?php echo $actividad_poa->getMetaPoaId() ?></td>
      <td><?php echo $actividad_poa->getProyectoId() ?></td>
      <td><?php echo $actividad_poa->getDescripcion() ?></td>
      <td><?php echo $actividad_poa->getResponsable() ?></td>
      <td><?php echo $actividad_poa->getObservaciones() ?></td>
      <td><?php echo $actividad_poa->getCreatedAt() ?></td>
      <td><?php echo $actividad_poa->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'actividadpoa/create') ?>
