<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:24:46
?>
<h1>actividadprocedimientopoa</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Procedimiento poa</th>
  <th>Actividad</th>
  <th>Descripcion</th>
  <th>Ponderacion</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($actividad_procedimiento_poas as $actividad_procedimiento_poa): ?>
<tr>
    <td><?php echo link_to($actividad_procedimiento_poa->getId(), 'actividadprocedimientopoa/show?id='.$actividad_procedimiento_poa->getId()) ?></td>
      <td><?php echo $actividad_procedimiento_poa->getProcedimientoPoaId() ?></td>
      <td><?php echo $actividad_procedimiento_poa->getActividad() ?></td>
      <td><?php echo $actividad_procedimiento_poa->getDescripcion() ?></td>
      <td><?php echo $actividad_procedimiento_poa->getPonderacion() ?></td>
      <td><?php echo $actividad_procedimiento_poa->getCreatedAt() ?></td>
      <td><?php echo $actividad_procedimiento_poa->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'actividadprocedimientopoa/create') ?>
