<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:24:46
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $actividad_procedimiento_poa->getId() ?></td>
</tr>
<tr>
<th>Procedimiento poa: </th>
<td><?php echo $actividad_procedimiento_poa->getProcedimientoPoaId() ?></td>
</tr>
<tr>
<th>Actividad: </th>
<td><?php echo $actividad_procedimiento_poa->getActividad() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $actividad_procedimiento_poa->getDescripcion() ?></td>
</tr>
<tr>
<th>Ponderacion: </th>
<td><?php echo $actividad_procedimiento_poa->getPonderacion() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $actividad_procedimiento_poa->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $actividad_procedimiento_poa->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'actividadprocedimientopoa/edit?id='.$actividad_procedimiento_poa->getId()) ?>
&nbsp;<?php echo link_to('list', 'actividadprocedimientopoa/list') ?>
