<?php
// auto-generated by sfPropelCrud
// date: 2010/09/16 23:20:05
?>
<h1>procedimiento</h1>

<table>
<thead>
<tr>
  <th>Procedimiento</th>
  <th>Descripcion</th>
  <th>Ponderacion</th>
</tr>
</thead>
<tbody>
<?php foreach ($procedimientos as $procedimiento): ?>
<tr>
    <td><?php echo link_to($procedimiento->getProcedimiento(), 'informes/Poaejecucion?procedimiento='.$procedimiento->getId()) ?></td>
      <td><?php echo $procedimiento->getProcedimiento()->getDescripcion() ?></td>
      <td><?php echo $procedimiento->getPonderacion() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'procedimiento/create') ?>
