<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:16:47
?>
<?php

/**
 * subactividadejecucion actions.
 *
 * @package    indicadores
 * @subpackage subactividadejecucion
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class subactividadejecucionActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('subactividadejecucion', 'list');
  }

  public function executeList()
  {
    $this->subactividad_ejecucions = SubactividadEjecucionPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->subactividad_ejecucion = SubactividadEjecucionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->subactividad_ejecucion);
  }

  public function executeCreate()
  {
    $this->subactividad_ejecucion = new SubactividadEjecucion();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->subactividad_ejecucion = SubactividadEjecucionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->subactividad_ejecucion);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $subactividad_ejecucion = new SubactividadEjecucion();
    }
    else
    {
      $subactividad_ejecucion = SubactividadEjecucionPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($subactividad_ejecucion);
    }

    $subactividad_ejecucion->setId($this->getRequestParameter('id'));
    $subactividad_ejecucion->setSubactividadProyectoId($this->getRequestParameter('subactividad_proyecto_id') ? $this->getRequestParameter('subactividad_proyecto_id') : null);
    $subactividad_ejecucion->setMes($this->getRequestParameter('mes'));
    $subactividad_ejecucion->setAvance($this->getRequestParameter('avance'));

    $subactividad_ejecucion->save();

    return $this->redirect('subactividadejecucion/show?id='.$subactividad_ejecucion->getId());
  }

  public function executeDelete()
  {
    $subactividad_ejecucion = SubactividadEjecucionPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($subactividad_ejecucion);

    $subactividad_ejecucion->delete();

    return $this->redirect('subactividadejecucion/list');
  }
}
