<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:16:47
?>
<?php use_helper('Object') ?>

<?php if ($subactividad->getMesMedicion() > 0): ?>
<?php echo form_tag('subactividadejecucion/update') ?>

<?php echo object_input_hidden_tag($subactividad_ejecucion, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Subactividad proyecto:</th>
  <td><?php echo $subactividad->getDescripcion(); ?>
    <?php echo input_hidden_tag('subactividad_proyecto_id', $subactividad->getId()) ?>
  </td>
</tr>
<tr>
  <th>Mes:</th>
  <td><?php echo $subactividad->getMesMedicion(); ?> de <?php echo $subactividad->getDuracion(); ?>
    <?php echo input_hidden_tag('mes', $subactividad->getMesMedicion()) ?>
</td>
</tr>
<tr>
  <th>Avance:</th>
  <td><?php echo object_input_tag($subactividad_ejecucion, 'getAvance', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($subactividad_ejecucion->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'subactividadejecucion/delete?id='.$subactividad_ejecucion->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'subactividadejecucion/show?id='.$subactividad_ejecucion->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'subactividadejecucion/list') ?>
<?php endif; ?>
</form>
<?php else: ?>
<strong>Se han realizado todas las mediciones</strong>
<?php endif; ?>
