<?php
// auto-generated by sfPropelCrud
// date: 2010/08/03 04:05:27
?>
<h1>subactividadejecucion</h1>

<table class="data">
<thead>
<tr>
  <th>Id</th>
  <th>Subactividad proyecto</th>
  <th>Mes</th>
  <th>Descripcion</th>
  <th>Avance</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($subactividad_ejecucions as $subactividad_ejecucion): ?>
<tr>
    <td><?php echo link_to($subactividad_ejecucion->getId(), 'subactividadejecucion/show?id='.$subactividad_ejecucion->getId()) ?></td>
      <td><?php echo $subactividad_ejecucion->getSubactividadProyectoId() ?></td>
      <td><?php echo $subactividad_ejecucion->getMes() ?></td>
      <td><?php echo $subactividad_ejecucion->getDescripcion() ?></td>
      <td><?php echo $subactividad_ejecucion->getAvance() ?></td>
      <td><?php echo $subactividad_ejecucion->getCreatedAt() ?></td>
      <td><?php echo $subactividad_ejecucion->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'subactividadejecucion/create') ?>
