<?php
// auto-generated by sfPropelCrud
// date: 2010/08/03 04:05:27
?>
<table class="data">
<tbody>
<tr>
<th>Subactividad proyecto: </th>
<td><?php echo $subactividad_ejecucion->getSubactividadProyecto() ?></td>
</tr>
<tr>
<th>Mes: </th>
<td><?php echo $subactividad_ejecucion->getMes() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $subactividad_ejecucion->getDescripcion() ?></td>
</tr>
<tr>
<th>Avance: </th>
<td><?php echo $subactividad_ejecucion->getAvance() ?></td>
</tr>
</tbody>
</table>
<hr />
