<?php
// auto-generated by sfPropelCrud
// date: 2010/08/03 04:05:27
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $subactividad_ejecucion->getId() ?></td>
</tr>
<tr>
<th>Subactividad proyecto: </th>
<td><?php echo $subactividad_ejecucion->getSubactividadProyectoId() ?></td>
</tr>
<tr>
<th>Mes: </th>
<td><?php echo $subactividad_ejecucion->getMes() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $subactividad_ejecucion->getDescripcion() ?></td>
</tr>
<tr>
<th>Avance: </th>
<td><?php echo $subactividad_ejecucion->getAvance() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $subactividad_ejecucion->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $subactividad_ejecucion->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'subactividadejecucion/edit?id='.$subactividad_ejecucion->getId()) ?>
&nbsp;<?php echo link_to('list', 'subactividadejecucion/list') ?>
