<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:21:03
?>
<?php

/**
 * localidad actions.
 *
 * @package    indicadores
 * @subpackage localidad
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class localidadActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('localidad', 'list');
  }

  public function executeList()
  {
    $this->localidads = LocalidadPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->localidad = LocalidadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->localidad);
  }

  public function executeCreate()
  {
    $this->localidad = new Localidad();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->localidad = LocalidadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->localidad);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $localidad = new Localidad();
    }
    else
    {
      $localidad = LocalidadPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($localidad);
    }

    $localidad->setId($this->getRequestParameter('id'));
    $localidad->setLocalidad($this->getRequestParameter('localidad'));

    $localidad->save();

    return $this->redirect('localidad/show?id='.$localidad->getId());
  }

  public function executeDelete()
  {
    $localidad = LocalidadPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($localidad);

    $localidad->delete();

    return $this->redirect('localidad/list');
  }
}
