<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:25:11
?>
<?php

/**
 * componenteact actions.
 *
 * @package    indicadores
 * @subpackage componenteact
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class componenteactActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('componenteact', 'list');
  }

  public function executeList()
  {
    $this->componente_actividads = ComponenteActividadPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->componente_actividad = ComponenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->componente_actividad);
  }

  public function executeCreate()
  {
    $this->componente_actividad = new ComponenteActividad();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->componente_actividad = ComponenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->componente_actividad);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $componente_actividad = new ComponenteActividad();
    }
    else
    {
      $componente_actividad = ComponenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($componente_actividad);
    }

    $componente_actividad->setId($this->getRequestParameter('id'));
    $componente_actividad->setComponenteId($this->getRequestParameter('componente_id') ? $this->getRequestParameter('componente_id') : null);
    $componente_actividad->setActividadId($this->getRequestParameter('actividad_id') ? $this->getRequestParameter('actividad_id') : null);
    $componente_actividad->setMonto($this->getRequestParameter('monto'));

    $componente_actividad->save();

    return $this->redirect('componenteact/show?id='.$componente_actividad->getId());
  }

  public function executeDelete()
  {
    $componente_actividad = ComponenteActividadPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($componente_actividad);

    $componente_actividad->delete();

    return $this->redirect('componenteact/list');
  }
}
