<?php
// auto-generated by sfPropelCrud
// date: 2009/02/04 17:13:23
?>
<?php use_helper('Object') ?>

<?php echo form_tag('indicadorvariable/update') ?>

<?php echo object_input_hidden_tag($indicador_variable, 'getId') ?>

<table class="data">
<tbody>
<tr>
  <th>Indicador:</th>
  <td><?php echo object_select_tag($indicador_variable, 'getIndicadorId', array (
  'related_class' => 'Indicador',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Variable:</th>
  <td><?php echo object_select_tag($indicador_variable, 'getVariableId', array (
  'related_class' => 'Variable',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($indicador_variable->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'indicadorvariable/delete?id='.$indicador_variable->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'indicadorvariable/show?id='.$indicador_variable->getId(), 'class="button"') ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'indicadorvariable/list', 'class="button"') ?>
<?php endif; ?>
</form>
