<?php
// auto-generated by sfPropelCrud
// date: 2009/02/04 17:13:23
?>
<h1>indicadorvariable</h1>

<table class="data">
<thead>
<tr>
  <th>Indicador</th>
  <th>Variables</th>
</tr>
</thead>
<tbody>
<?php foreach ($indicadores as $i => $indicador): ?>
<tr class="<?php echo fmod($i, 2) ? 'par' : 'impar' ?>">
    <td><?php echo link_to($indicador->getIndicador(), 'indicadorvariable/list?indicador='.$indicador->getId()) ?></td>
    <td><?php foreach ($indicador->getArrayVariables() as $variable): ?>
      <?php echo $variable ?><br />
    <?php endforeach; ?>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
