<?php
// auto-generated by sfPropelCrud
// date: 2009/02/04 17:13:23
?>
<table class="data">
<tbody>
<tr>
<th>Indicador: </th>
<td><?php echo $indicador_variable->getIndicador() ?></td>
</tr>
<tr>
<th>Variable: </th>
<td><?php echo $indicador_variable->getVariable() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'indicadorvariable/edit?id='.$indicador_variable->getId(), 'class="button"') ?>
&nbsp;<?php echo link_to('Regresar a la lista', 'indicadorvariable/list', 'class="button"') ?>
