<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:21:03
?>
<?php use_helper('Object') ?>

<?php echo form_tag('localidad/update') ?>

<?php echo object_input_hidden_tag($localidad, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Localidad:</th>
  <td><?php echo object_input_tag($localidad, 'getLocalidad', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($localidad->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'localidad/delete?id='.$localidad->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'localidad/show?id='.$localidad->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'localidad/list') ?>
<?php endif; ?>
</form>
