<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:13:10
?>
<?php use_helper('Object') ?>

<?php echo form_tag('localidad/update') ?>

<?php echo object_input_hidden_tag($localidad, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Localidad:</th>
  <td><?php echo object_input_tag($localidad, 'getLocalidad', array (
  'size' => 50,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($localidad->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'localidad/delete?id='.$localidad->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'localidad/show?id='.$localidad->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'localidad/list') ?>
<?php endif; ?>
</form>
