<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:13:10
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $localidad->getId() ?></td>
</tr>
<tr>
<th>Localidad: </th>
<td><?php echo $localidad->getLocalidad() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'localidad/edit?id='.$localidad->getId()) ?>
&nbsp;<?php echo link_to('list', 'localidad/list') ?>
