<?php
// auto-generated by sfPropelCrud
// date: 2010/08/03 01:29:27
?>
<?php

/**
 * metaproyecto actions.
 *
 * @package    indicadores
 * @subpackage metaproyecto
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class metaproyectoActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('metaproyecto', 'list');
  }

  public function executeList()
  {
    $this->meta_proyectos = MetaProyectoPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->meta_proyecto = MetaProyectoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->meta_proyecto);
  }

  public function executeCreate()
  {
    $this->meta_proyecto = new MetaProyecto();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->meta_proyecto = MetaProyectoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->meta_proyecto);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $meta_proyecto = new MetaProyecto();
    }
    else
    {
      $meta_proyecto = MetaProyectoPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($meta_proyecto);
    }

    $meta_proyecto->setId($this->getRequestParameter('id'));
    $meta_proyecto->setMetaPdId($this->getRequestParameter('meta_pd_id') ? $this->getRequestParameter('meta_pd_id') : null);
    $meta_proyecto->setProyectoId($this->getRequestParameter('proyecto_id') ? $this->getRequestParameter('proyecto_id') : null);
    $meta_proyecto->setCodigo($this->getRequestParameter('codigo'));
    $meta_proyecto->setMeta($this->getRequestParameter('meta'));
    $meta_proyecto->setTipo($this->getRequestParameter('tipo'));
    $meta_proyecto->setObjetivoId($this->getRequestParameter('objetivo_id') ? $this->getRequestParameter('objetivo_id') : null);
    $meta_proyecto->setDescripcion($this->getRequestParameter('descripcion'));
    $meta_proyecto->setAnualizacionId($this->getRequestParameter('anualizacion_id') ? $this->getRequestParameter('anualizacion_id') : null);

    $meta_proyecto->save();

    return $this->redirect('metaproyecto/show?id='.$meta_proyecto->getId());
  }

  public function executeDelete()
  {
    $meta_proyecto = MetaProyectoPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($meta_proyecto);

    $meta_proyecto->delete();

    return $this->redirect('metaproyecto/list');
  }
}
