<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:25:44
?>
<?php use_helper('Object') ?>
<h3>Subactividad: <?php echo $subactividad->getDescripcion(); ?></h3>
<h3>Duracion: <?php echo $subactividad->getDuracion(); ?> meses</h3>
<h3>Porcentaje Avance: <?php echo $subactividad->getEjecucion(); ?>%</h3>
<?php if ($subactividad->getMesMedicion() > 0): ?>

<?php echo form_tag('subactividadprocedimientopoaejecucion/update') ?>

<?php echo object_input_hidden_tag($subactividad_procedimiento_poa_ejecucion, 'getId') ?>
<?php echo input_hidden_tag('subactividad_procedimiento_poa_id', $subactividad->getId()) ?>

<table class="data">
<tbody>
<tr>
  <th>Mes*:</th>
  <td>
  <?php echo $subactividad->getMesMedicion(); ?> de <?php echo $subactividad->getDuracion(); ?>
  <?php echo object_input_tag($subactividad_procedimiento_poa_ejecucion, 'getMes', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Descripcion*:</th>
  <td><?php echo object_textarea_tag($subactividad_procedimiento_poa_ejecucion, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Avance:</th>
  <td><?php echo object_input_tag($subactividad_procedimiento_poa_ejecucion, 'getAvance', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($subactividad_procedimiento_poa_ejecucion->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'subactividadprocedimientopoaejecucion/delete?id='.$subactividad_procedimiento_poa_ejecucion->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'subactividadprocedimientopoaejecucion/show?id='.$subactividad_procedimiento_poa_ejecucion->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'subactividadprocedimientopoaejecucion/list') ?>
<?php endif; ?>
</form>
<?php else: ?>
<h1><strong>Se han realizado todas las mediciones</strong></h1>
<?php endif; ?>
