<?php
// auto-generated by sfPropelCrud
// date: 2010/09/20 19:42:22
?>
<h1>subactividadpoaejecucion</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Subactividad proyecto</th>
  <th>Mes</th>
  <th>Descripcion</th>
  <th>Avance</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($subactividad_poa_ejecucions as $subactividad_poa_ejecucion): ?>
<tr>
    <td><?php echo link_to($subactividad_poa_ejecucion->getId(), 'subactividadpoaejecucion/show?id='.$subactividad_poa_ejecucion->getId()) ?></td>
      <td><?php echo $subactividad_poa_ejecucion->getSubactividadProyectoId() ?></td>
      <td><?php echo $subactividad_poa_ejecucion->getMes() ?></td>
      <td><?php echo $subactividad_poa_ejecucion->getDescripcion() ?></td>
      <td><?php echo $subactividad_poa_ejecucion->getAvance() ?></td>
      <td><?php echo $subactividad_poa_ejecucion->getCreatedAt() ?></td>
      <td><?php echo $subactividad_poa_ejecucion->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'subactividadpoaejecucion/create') ?>
