<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:15:44
?>
<?php

/**
 * tipogasto actions.
 *
 * @package    indicadores
 * @subpackage tipogasto
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class tipogastoActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('tipogasto', 'list');
  }

  public function executeList()
  {
    $this->tipo_gastos = TipoGastoPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->tipo_gasto = TipoGastoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->tipo_gasto);
  }

  public function executeCreate()
  {
    $this->tipo_gasto = new TipoGasto();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->tipo_gasto = TipoGastoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->tipo_gasto);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $tipo_gasto = new TipoGasto();
    }
    else
    {
      $tipo_gasto = TipoGastoPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($tipo_gasto);
    }

    $tipo_gasto->setId($this->getRequestParameter('id'));
    $tipo_gasto->setTipoGasto($this->getRequestParameter('tipo_gasto'));

    $tipo_gasto->save();

    return $this->redirect('tipogasto/show?id='.$tipo_gasto->getId());
  }

  public function executeDelete()
  {
    $tipo_gasto = TipoGastoPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($tipo_gasto);

    $tipo_gasto->delete();

    return $this->redirect('tipogasto/list');
  }
}
