<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:11
?>
<h1>fuenteactividad</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Fuente</th>
  <th>Actividad</th>
  <th>Monto</th>
</tr>
</thead>
<tbody>
<?php foreach ($fuente_actividads as $fuente_actividad): ?>
<tr>
    <td><?php echo link_to($fuente_actividad->getId(), 'fuenteactividad/show?id='.$fuente_actividad->getId()) ?></td>
      <td><?php echo $fuente_actividad->getFuenteId() ?></td>
      <td><?php echo $fuente_actividad->getActividadId() ?></td>
      <td><?php echo $fuente_actividad->getMonto() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'fuenteactividad/create') ?>
