<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:11
?>
<h1>Fuentes por Actividad</h1>

<table class="data">
<thead>
<tr>
  <th>Fuente</th>
  <th>Actividad</th>
  <th>Monto</th>
</tr>
</thead>
<tbody>
<?php foreach ($fuente_actividads as $fuente_actividad): ?>
<tr>
    <td><?php echo link_to($fuente_actividad->getFuente()), 'fuenteactividad/edit?id='.$fuente_actividad->getId().'&actividad='.$fuente_actividad->getActividadId()) ?></td>
      <td><?php echo $fuente_actividad->getActividad()->getDescripcion() ?></td>
      <td><?php echo $fuente_actividad->getMonto() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
