<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/07/20 02:22:31

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root@localhost/indicadores',
), 'propel');
$this->databases['propel'] = $database;
