<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:25:30
?>
<?php use_helper('Object') ?>
<?php use_helper('Javascript') ?>

<?php echo form_tag('subactividadprocedimientopoa/update') ?>

<?php echo object_input_hidden_tag($subactividad_procedimiento_poa, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Procedimiento</th>
  <td><?php echo select_tag('procedimiento_id', objects_for_select($procedimiento, 'getId', '__toString', '', 'include_blank=true')) ?>
        <?php
          echo observe_field('procedimiento_id', array(
          'update'   => 'actividad_procedimiento_id',
          'url'      => 'ajax/ActividadProcedimientoporProcedimiento',
          'with'     => "'procedimiento=' + value",
          'script'   => true,
          'loading' => "Element.show('indicator')",
          'complete' => "Element.hide('indicator')",
        ));
        ?>
 </td>

</tr>
<tr>
  <th>Actividad procedimiento:</th>
  <td><?php echo object_select_tag($subactividad_procedimiento_poa, 'getActividadProcedimientoId', array (
  'related_class' => 'ActividadProcedimientoPoa',
  'include_blank' => true,
)) ?>
  <?php
    echo observe_field('actividad_procedimiento_id', array(
    'update'   => 'pond',
    'url'      => 'ajax/SubactividadProcedimiento',
    'with'     => "'actividad=' + value",
    'script'   => true,
    ));
  ?>
  </td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($subactividad_procedimiento_poa, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Responsable:</th>
  <td><?php echo object_input_tag($subactividad_procedimiento_poa, 'getResponsable', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Entregable*:</th>
  <td><?php echo object_textarea_tag($subactividad_procedimiento_poa, 'getEntregable', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Fecha inicio*:</th>
  <td><?php echo object_input_date_tag($subactividad_procedimiento_poa, 'getFechaInicio', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Duracion*:</th>
  <td><?php echo object_input_tag($subactividad_procedimiento_poa, 'getDuracion', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Ponderacion*:</th>
  <td><?php echo object_input_tag($subactividad_procedimiento_poa, 'getPonderacion', array (
  'size' => 7,
)) ?>&nbsp;Ponderacion Acumulada <div id="pond" style="display: inline"></div>%</td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($subactividad_procedimiento_poa->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'subactividadprocedimientopoa/delete?id='.$subactividad_procedimiento_poa->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'subactividadprocedimientopoa/show?id='.$subactividad_procedimiento_poa->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'subactividadprocedimientopoa/list') ?>
<?php endif; ?>
</form>
