<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:25:30
?>
<?php use_helper('Object') ?>

<?php echo form_tag('subactividadprocedimientopoa/update') ?>

<?php echo object_input_hidden_tag($subactividad_procedimiento_poa, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Actividad procedimiento:</th>
  <td><?php echo object_select_tag($subactividad_procedimiento_poa, 'getActividadProcedimientoId', array (
  'related_class' => 'ActividadProcedimientoPoa',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($subactividad_procedimiento_poa, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Responsable:</th>
  <td><?php echo object_input_tag($subactividad_procedimiento_poa, 'getResponsable', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Entregable*:</th>
  <td><?php echo object_textarea_tag($subactividad_procedimiento_poa, 'getEntregable', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Fecha inicio*:</th>
  <td><?php echo object_input_date_tag($subactividad_procedimiento_poa, 'getFechaInicio', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Duracion*:</th>
  <td><?php echo object_input_tag($subactividad_procedimiento_poa, 'getDuracion', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Ponderacion*:</th>
  <td><?php echo object_input_tag($subactividad_procedimiento_poa, 'getPonderacion', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($subactividad_procedimiento_poa->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'subactividadprocedimientopoa/delete?id='.$subactividad_procedimiento_poa->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'subactividadprocedimientopoa/show?id='.$subactividad_procedimiento_poa->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'subactividadprocedimientopoa/list') ?>
<?php endif; ?>
</form>
