<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:25:30
?>
<h1>SubActividades Procedimiento POA</h1>

<table class="data">
<thead>
<tr>
  <th>Actividad procedimiento</th>
  <th>Descripcion</th>
  <th>Responsable</th>
  <th>Entregable</th>
  <th>Fecha inicio</th>
  <th>Duracion</th>
  <th>Ponderacion</th>
</tr>
</thead>
<tbody>
<?php foreach ($subactividad_procedimiento_poas as $subactividad_procedimiento_poa): ?>
<tr>
    <td><?php echo link_to($subactividad_procedimiento_poa->getActividadProcedimientoId(), 'subactividadprocedimientopoa/show?id='.$subactividad_procedimiento_poa->getId()) ?></td>
      <td><?php echo $subactividad_procedimiento_poa->getDescripcion() ?></td>
      <td><?php echo $subactividad_procedimiento_poa->getResponsable() ?></td>
      <td><?php echo $subactividad_procedimiento_poa->getEntregable() ?></td>
      <td><?php echo $subactividad_procedimiento_poa->getFechaInicio() ?></td>
      <td><?php echo $subactividad_procedimiento_poa->getDuracion() ?></td>
      <td><?php echo $subactividad_procedimiento_poa->getPonderacion() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
