<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 15:35:10
?>
<?php use_helper('Object') ?>

<?php echo form_tag('macroproceso/update') ?>

<?php echo object_input_hidden_tag($macroproceso, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Nombre:</th>
  <td><?php echo object_input_tag($macroproceso, 'getNombre', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($macroproceso, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($macroproceso->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'macroproceso/delete?id='.$macroproceso->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'macroproceso/show?id='.$macroproceso->getId(), 'class="button"') ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'macroproceso/list', 'class="button"') ?>
<?php endif; ?>
</form>
