<?php
// auto-generated by sfPropelCrud
// date: 2009/03/10 15:35:10
?>
<table class="data">
<tbody>
<tr>
<th>Nombre: </th>
<td><?php echo $macroproceso->getNombre() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $macroproceso->getDescripcion() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'macroproceso/edit?id='.$macroproceso->getId(), 'class="button"') ?>
&nbsp;<?php echo link_to('Regresar a la lista', 'macroproceso/list', 'class="button"') ?>
