<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:15:40
?>
<?php

/**
 * proyecto actions.
 *
 * @package    indicadores
 * @subpackage proyecto
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class proyectoActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('proyecto', 'list');
  }

  public function executeList()
  {
    $this->proyectos = ProyectoPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->proyecto = ProyectoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->proyecto);
  }

  public function executeCreate()
  {
    $this->proyecto = new Proyecto();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->proyecto = ProyectoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->proyecto);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $proyecto = new Proyecto();
    }
    else
    {
      $proyecto = ProyectoPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($proyecto);
    }

    $proyecto->setId($this->getRequestParameter('id'));
    $proyecto->setMetaProyectoId($this->getRequestParameter('meta_proyecto_id') ? $this->getRequestParameter('meta_proyecto_id') : null);
    $proyecto->setAnualizacionId($this->getRequestParameter('anualizacion_id') ? $this->getRequestParameter('anualizacion_id') : null);
    $proyecto->setCodigo($this->getRequestParameter('codigo'));
    $proyecto->setProyecto($this->getRequestParameter('proyecto'));
    $proyecto->setDescripcion($this->getRequestParameter('descripcion'));
    $proyecto->setMagnitud($this->getRequestParameter('magnitud'));
    $proyecto->setProgramaInterno($this->getRequestParameter('programa_interno'));

    $proyecto->save();

    return $this->redirect('proyecto/show?id='.$proyecto->getId());
  }

  public function executeDelete()
  {
    $proyecto = ProyectoPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($proyecto);

    $proyecto->delete();

    return $this->redirect('proyecto/list');
  }
}
