<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:15:08
?>
<?php use_helper('Object') ?>

<?php echo form_tag('crp/update') ?>

<?php echo object_input_hidden_tag($crp, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Numero:</th>
  <td><?php echo object_input_tag($crp, 'getNumero', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Fecha:</th>
  <td><?php echo object_input_date_tag($crp, 'getFecha', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Monto:</th>
  <td><?php echo object_input_tag($crp, 'getMonto', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($crp->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'crp/delete?id='.$crp->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'crp/show?id='.$crp->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'crp/list') ?>
<?php endif; ?>
</form>
