<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:15:08
?>
<h1>crp</h1>

<table class="data">
<thead>
<tr>
  <th>Numero</th>
  <th>Fecha</th>
  <th>Monto</th>
</tr>
</thead>
<tbody>
<?php foreach ($crps as $crp): ?>
<tr>
    <td><?php echo link_to($crp->getNumero(), 'crp/show?id='.$crp->getId()) ?></td>
      <td><?php echo $crp->getNumero() ?></td>
      <td><?php echo $crp->getFecha() ?></td>
      <td><?php echo $crp->getMonto() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
