<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:22:51
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $crp->getId() ?></td>
</tr>
<tr>
<th>Numero: </th>
<td><?php echo $crp->getNumero() ?></td>
</tr>
<tr>
<th>Fecha: </th>
<td><?php echo $crp->getFecha() ?></td>
</tr>
<tr>
<th>Monto: </th>
<td><?php echo $crp->getMonto() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'crp/edit?id='.$crp->getId()) ?>
&nbsp;<?php echo link_to('list', 'crp/list') ?>
