<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:25:44
?>
<?php use_helper('Object') ?>

<?php echo form_tag('subactividadprocedimientopoaejecucion/update') ?>

<?php echo object_input_hidden_tag($subactividad_procedimiento_poa_ejecucion, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Subactividad poa:</th>
  <td><?php echo object_select_tag($subactividad_procedimiento_poa_ejecucion, 'getSubactividadPoaId', array (
  'related_class' => 'SubactividadProcedimientoPoa',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Mes*:</th>
  <td><?php echo object_input_tag($subactividad_procedimiento_poa_ejecucion, 'getMes', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Descripcion*:</th>
  <td><?php echo object_textarea_tag($subactividad_procedimiento_poa_ejecucion, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Avance:</th>
  <td><?php echo object_input_tag($subactividad_procedimiento_poa_ejecucion, 'getAvance', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($subactividad_procedimiento_poa_ejecucion->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'subactividadprocedimientopoaejecucion/delete?id='.$subactividad_procedimiento_poa_ejecucion->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'subactividadprocedimientopoaejecucion/show?id='.$subactividad_procedimiento_poa_ejecucion->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'subactividadprocedimientopoaejecucion/list') ?>
<?php endif; ?>
</form>
