<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:25:44
?>
<table class="data">
<tbody>
<tr>
<th>Subactividad poa: </th>
<td><?php echo $subactividad_procedimiento_poa_ejecucion->getSubactividadProcedimientoPoa() ?></td>
</tr>
<tr>
<th>Mes: </th>
<td><?php echo $subactividad_procedimiento_poa_ejecucion->getMes() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $subactividad_procedimiento_poa_ejecucion->getDescripcion() ?></td>
</tr>
<tr>
<th>Avance: </th>
<td><?php echo $subactividad_procedimiento_poa_ejecucion->getAvance() ?></td>
</tr>
</tbody>
</table>
<hr />
