<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:15:18
?>
<?php

/**
 * crpactividad actions.
 *
 * @package    indicadores
 * @subpackage crpactividad
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class crpactividadActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('crpactividad', 'list');
  }

  public function executeList()
  {
    $this->crp_actividads = CrpActividadPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->crp_actividad = CrpActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->crp_actividad);
  }

  public function executeCreate()
  {
    $this->crp_actividad = new CrpActividad();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->crp_actividad = CrpActividadPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->crp_actividad);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $crp_actividad = new CrpActividad();
    }
    else
    {
      $crp_actividad = CrpActividadPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($crp_actividad);
    }

    $crp_actividad->setId($this->getRequestParameter('id'));
    $crp_actividad->setCrpId($this->getRequestParameter('crp_id') ? $this->getRequestParameter('crp_id') : null);
    $crp_actividad->setActividadId($this->getRequestParameter('actividad_id') ? $this->getRequestParameter('actividad_id') : null);

    $crp_actividad->save();

    return $this->redirect('crpactividad/show?id='.$crp_actividad->getId());
  }

  public function executeDelete()
  {
    $crp_actividad = CrpActividadPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($crp_actividad);

    $crp_actividad->delete();

    return $this->redirect('crpactividad/list');
  }
}
