<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:16:14
?>
<?php

/**
 * conceptogasto actions.
 *
 * @package    indicadores
 * @subpackage conceptogasto
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class conceptogastoActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('conceptogasto', 'list');
  }

  public function executeList()
  {
    $this->concepto_gastos = ConceptoGastoPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->concepto_gasto = ConceptoGastoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->concepto_gasto);
  }

  public function executeCreate()
  {
    $this->concepto_gasto = new ConceptoGasto();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->concepto_gasto = ConceptoGastoPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->concepto_gasto);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $concepto_gasto = new ConceptoGasto();
    }
    else
    {
      $concepto_gasto = ConceptoGastoPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($concepto_gasto);
    }

    $concepto_gasto->setId($this->getRequestParameter('id'));
    $concepto_gasto->setConceptoGasto($this->getRequestParameter('concepto_gasto'));

    $concepto_gasto->save();

    return $this->redirect('conceptogasto/show?id='.$concepto_gasto->getId());
  }

  public function executeDelete()
  {
    $concepto_gasto = ConceptoGastoPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($concepto_gasto);

    $concepto_gasto->delete();

    return $this->redirect('conceptogasto/list');
  }
}
