<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:34
?>
<?php use_helper('Object') ?>

<?php echo form_tag('componenteproyecto/update') ?>

<?php echo object_input_hidden_tag($componente_proyecto, 'getId') ?>

<table class="data">
<tbody>
<tr>
  <th>Componente:</th>
  <td><?php echo object_select_tag($componente_proyecto, 'getComponenteId', array (
  'related_class' => 'Componente',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Proyecto:</th>
  <td><?php echo object_select_tag($componente_proyecto, 'getProyectoId', array (
  'related_class' => 'Proyecto',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Monto:</th>
  <td><?php echo object_input_tag($componente_proyecto, 'getMonto', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($componente_proyecto->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'componenteproyecto/delete?id='.$componente_proyecto->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'componenteproyecto/show?id='.$componente_proyecto->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'componenteproyecto/list') ?>
<?php endif; ?>
</form>
