<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:34
?>
<?php use_helper('Object') ?>

<?php echo form_tag('componenteproyecto/update') ?>

<?php echo object_input_hidden_tag($componente_proyecto, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Componente:</th>
  <td><?php echo object_select_tag($componente_proyecto, 'getComponenteId', array (
  'related_class' => 'Componente',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Proyecto:</th>
  <td><?php echo object_select_tag($componente_proyecto, 'getProyectoId', array (
  'related_class' => 'Proyecto',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Monto:</th>
  <td><?php echo object_input_tag($componente_proyecto, 'getMonto', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($componente_proyecto->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'componenteproyecto/delete?id='.$componente_proyecto->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'componenteproyecto/show?id='.$componente_proyecto->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'componenteproyecto/list') ?>
<?php endif; ?>
</form>
