<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:34
?>
<h1>componenteproyecto</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Componente</th>
  <th>Proyecto</th>
  <th>Monto</th>
</tr>
</thead>
<tbody>
<?php foreach ($componente_proyectos as $componente_proyecto): ?>
<tr>
    <td><?php echo link_to($componente_proyecto->getId(), 'componenteproyecto/show?id='.$componente_proyecto->getId()) ?></td>
      <td><?php echo $componente_proyecto->getComponenteId() ?></td>
      <td><?php echo $componente_proyecto->getProyectoId() ?></td>
      <td><?php echo $componente_proyecto->getMonto() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'componenteproyecto/create') ?>
