<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:34
?>
<h1>Programacion Componentes por Proyecto</h1>

<table class="data">
<thead>
<tr>
  <th>Componente</th>
  <th>Proyecto</th>
  <th>Monto</th>
</tr>
</thead>
<tbody>
<?php foreach ($componente_proyectos as $componente_proyecto): ?>
<tr>
    <td><?php echo link_to($componente_proyecto->getComponente(), 'componenteproyecto/show?id='.$componente_proyecto->getId()) ?></td>
      <td><?php echo $componente_proyecto->getProyecto() ?></td>
      <td><?php echo $componente_proyecto->getMonto() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
