<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:34
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $componente_proyecto->getId() ?></td>
</tr>
<tr>
<th>Componente: </th>
<td><?php echo $componente_proyecto->getComponenteId() ?></td>
</tr>
<tr>
<th>Proyecto: </th>
<td><?php echo $componente_proyecto->getProyectoId() ?></td>
</tr>
<tr>
<th>Monto: </th>
<td><?php echo $componente_proyecto->getMonto() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'componenteproyecto/edit?id='.$componente_proyecto->getId()) ?>
&nbsp;<?php echo link_to('list', 'componenteproyecto/list') ?>
