<?php
// auto-generated by sfPropelCrud
// date: 2010/07/01 09:24:23
?>
<?php use_helper('Object') ?>

<?php echo form_tag('actividad/update') ?>

<?php echo object_input_hidden_tag($actividad, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Proyecto inversion:</th>
  <td><?php echo object_select_tag($actividad, 'getProyectoInversionId', array (
  'related_class' => 'ProyectoInversion',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Descripcion:</th>
  <td><?php echo object_textarea_tag($actividad, 'getDescripcion', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Tipo gasto:</th>
  <td><?php echo object_input_tag($actividad, 'getTipoGasto', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Componente sector:</th>
  <td><?php echo object_input_tag($actividad, 'getComponenteSector', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Concepto gasto:</th>
  <td><?php echo object_input_tag($actividad, 'getConceptoGasto', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Mes etapa contractual:</th>
  <td><?php echo object_input_tag($actividad, 'getMesEtapaContractual', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Mes ejecucion:</th>
  <td><?php echo object_input_tag($actividad, 'getMesEjecucion', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Reservas:</th>
  <td><?php echo object_input_tag($actividad, 'getReservas', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Area responsable:</th>
  <td><?php echo object_input_tag($actividad, 'getAreaResponsable', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Valor proceso:</th>
  <td><?php echo object_input_tag($actividad, 'getValorProceso', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Numero solicitud:</th>
  <td><?php echo object_input_tag($actividad, 'getNumeroSolicitud', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Fecha solicitud:</th>
  <td><?php echo object_input_date_tag($actividad, 'getFechaSolicitud', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Fecha contrato:</th>
  <td><?php echo object_input_date_tag($actividad, 'getFechaContrato', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Fecha acta inicio:</th>
  <td><?php echo object_input_date_tag($actividad, 'getFechaActaInicio', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Fecha terminacion:</th>
  <td><?php echo object_input_date_tag($actividad, 'getFechaTerminacion', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Fecha liquidacion:</th>
  <td><?php echo object_input_date_tag($actividad, 'getFechaLiquidacion', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Plazo meses:</th>
  <td><?php echo object_input_tag($actividad, 'getPlazoMeses', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Contrato:</th>
  <td><?php echo object_select_tag($actividad, 'getContratoId', array (
  'related_class' => 'Contrato',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Clase contrato:</th>
  <td><?php echo object_input_tag($actividad, 'getClaseContrato', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Estado:</th>
  <td><?php echo object_input_tag($actividad, 'getEstado', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Existencia contrato numero:</th>
  <td><?php echo object_input_tag($actividad, 'getExistenciaContratoNumero', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Giros:</th>
  <td><?php echo object_input_tag($actividad, 'getGiros', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Saldo:</th>
  <td><?php echo object_input_tag($actividad, 'getSaldo', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($actividad->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'actividad/delete?id='.$actividad->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'actividad/show?id='.$actividad->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'actividad/list') ?>
<?php endif; ?>
</form>
