<?php
// auto-generated by sfPropelCrud
// date: 2010/07/01 09:24:23
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $actividad->getId() ?></td>
</tr>
<tr>
<th>Proyecto inversion: </th>
<td><?php echo $actividad->getProyectoInversionId() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $actividad->getDescripcion() ?></td>
</tr>
<tr>
<th>Tipo gasto: </th>
<td><?php echo $actividad->getTipoGasto() ?></td>
</tr>
<tr>
<th>Componente sector: </th>
<td><?php echo $actividad->getComponenteSector() ?></td>
</tr>
<tr>
<th>Concepto gasto: </th>
<td><?php echo $actividad->getConceptoGasto() ?></td>
</tr>
<tr>
<th>Mes etapa contractual: </th>
<td><?php echo $actividad->getMesEtapaContractual() ?></td>
</tr>
<tr>
<th>Mes ejecucion: </th>
<td><?php echo $actividad->getMesEjecucion() ?></td>
</tr>
<tr>
<th>Reservas: </th>
<td><?php echo $actividad->getReservas() ?></td>
</tr>
<tr>
<th>Area responsable: </th>
<td><?php echo $actividad->getAreaResponsable() ?></td>
</tr>
<tr>
<th>Valor proceso: </th>
<td><?php echo $actividad->getValorProceso() ?></td>
</tr>
<tr>
<th>Numero solicitud: </th>
<td><?php echo $actividad->getNumeroSolicitud() ?></td>
</tr>
<tr>
<th>Fecha solicitud: </th>
<td><?php echo $actividad->getFechaSolicitud() ?></td>
</tr>
<tr>
<th>Fecha contrato: </th>
<td><?php echo $actividad->getFechaContrato() ?></td>
</tr>
<tr>
<th>Fecha acta inicio: </th>
<td><?php echo $actividad->getFechaActaInicio() ?></td>
</tr>
<tr>
<th>Fecha terminacion: </th>
<td><?php echo $actividad->getFechaTerminacion() ?></td>
</tr>
<tr>
<th>Fecha liquidacion: </th>
<td><?php echo $actividad->getFechaLiquidacion() ?></td>
</tr>
<tr>
<th>Plazo meses: </th>
<td><?php echo $actividad->getPlazoMeses() ?></td>
</tr>
<tr>
<th>Contrato: </th>
<td><?php echo $actividad->getContratoId() ?></td>
</tr>
<tr>
<th>Clase contrato: </th>
<td><?php echo $actividad->getClaseContrato() ?></td>
</tr>
<tr>
<th>Estado: </th>
<td><?php echo $actividad->getEstado() ?></td>
</tr>
<tr>
<th>Existencia contrato numero: </th>
<td><?php echo $actividad->getExistenciaContratoNumero() ?></td>
</tr>
<tr>
<th>Giros: </th>
<td><?php echo $actividad->getGiros() ?></td>
</tr>
<tr>
<th>Saldo: </th>
<td><?php echo $actividad->getSaldo() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $actividad->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $actividad->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'actividad/edit?id='.$actividad->getId()) ?>
&nbsp;<?php echo link_to('list', 'actividad/list') ?>
