<?php
// auto-generated by sfPropelCrud
// date: 2010/09/24 15:58:02
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $actividad->getId() ?></td>
</tr>
<tr>
<th>Proyecto: </th>
<td><?php echo $actividad->getProyecto() ?></td>
</tr>
<tr>
<th>Descripcion: </th>
<td><?php echo $actividad->getDescripcion() ?></td>
</tr>
<tr>
<th>Tipo gasto: </th>
<td><?php echo $actividad->getTipoGasto() ?></td>
</tr>
<tr>
<th>Componente sector: </th>
<td><?php echo $actividad->getComponenteSector() ?></td>
</tr>
<tr>
<th>Concepto gasto: </th>
<td><?php echo $actividad->getConceptoGasto() ?></td>
</tr>
<tr>
<th>Cod app fvs: </th>
<td><?php echo $actividad->getCodAppFvs() ?></td>
</tr>
<tr>
<th>Meta proyecto: </th>
<td><?php echo $actividad->getMetaProyecto() ?></td>
</tr>
<tr>
<th>Inversion recurrente: </th>
<td><?php echo $actividad->getInversionRecurrente() ?></td>
</tr>
<tr>
<th>Mes etapa contractual: </th>
<td><?php echo $actividad->getMesEtapaContractual() ?></td>
</tr>
<tr>
<th>Mes inicio ejecucion: </th>
<td><?php echo $actividad->getMesInicioEjecucion() ?></td>
</tr>
<tr>
<th>Reservas: </th>
<td><?php echo $actividad->getReservas() ?></td>
</tr>
<tr>
<th>Area responsable: </th>
<td><?php echo $actividad->getDependencia() ?></td>
</tr>
<tr>
<th>Componente inversion: </th>
<td><?php echo $actividad->getComponente() ?></td>
</tr>
<tr>
<th>Plurianual programado: </th>
<td><?php echo $actividad->getPlurianualProgramado() ?></td>
</tr>
<tr>
<th>Numero solicitud: </th>
<td><?php echo $actividad->getNumeroSolicitud() ?></td>
</tr>
<tr>
<th>Cdp: </th>
<td><?php echo $actividad->getCdp() ?></td>
</tr>
<tr>
<th>Crp: </th>
<td><?php echo $actividad->getCrp() ?></td>
</tr>
<tr>
<th>Fecha solicitud: </th>
<td><?php echo $actividad->getFechaSolicitud() ?></td>
</tr>
<tr>
<th>Fecha contrato: </th>
<td><?php echo $actividad->getFechaContrato() ?></td>
</tr>
<tr>
<th>Fecha acta inicio: </th>
<td><?php echo $actividad->getFechaActaInicio() ?></td>
</tr>
<tr>
<th>Fecha terminacion: </th>
<td><?php echo $actividad->getFechaTerminacion() ?></td>
</tr>
<tr>
<th>Fecha liquidacion: </th>
<td><?php echo $actividad->getFechaLiquidacion() ?></td>
</tr>
<tr>
<th>Plazo meses: </th>
<td><?php echo $actividad->getPlazoMeses() ?></td>
</tr>
<tr>
<th>Contrato: </th>
<td><?php echo $actividad->getContrato() ?></td>
</tr>
<tr>
<th>Existencia contrato numero: </th>
<td><?php echo $actividad->getExistenciaContratoNumero() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $actividad->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $actividad->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'actividad/edit?id='.$actividad->getId(), 'class="button"') ?>
&nbsp;<?php echo link_to('Listar', 'actividad/list') ?>
