<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:20:47
?>
<?php

/**
 * proyectoinv actions.
 *
 * @package    indicadores
 * @subpackage proyectoinv
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class proyectoinvActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('proyectoinv', 'list');
  }

  public function executeList()
  {
    $this->proyecto_inversions = ProyectoInversionPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->proyecto_inversion = ProyectoInversionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->proyecto_inversion);
  }

  public function executeCreate()
  {
    $this->proyecto_inversion = new ProyectoInversion();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->proyecto_inversion = ProyectoInversionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->proyecto_inversion);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $proyecto_inversion = new ProyectoInversion();
    }
    else
    {
      $proyecto_inversion = ProyectoInversionPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($proyecto_inversion);
    }

    $proyecto_inversion->setId($this->getRequestParameter('id'));
    $proyecto_inversion->setMetaPdId($this->getRequestParameter('meta_pd_id') ? $this->getRequestParameter('meta_pd_id') : null);
    $proyecto_inversion->setCodigo($this->getRequestParameter('codigo'));
    $proyecto_inversion->setProyecto($this->getRequestParameter('proyecto'));

    $proyecto_inversion->save();

    return $this->redirect('proyectoinv/show?id='.$proyecto_inversion->getId());
  }

  public function executeDelete()
  {
    $proyecto_inversion = ProyectoInversionPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($proyecto_inversion);

    $proyecto_inversion->delete();

    return $this->redirect('proyectoinv/list');
  }
}
