<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:20:00
?>
<?php

/**
 * actividadpoa actions.
 *
 * @package    indicadores
 * @subpackage actividadpoa
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class actividadpoaActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('actividadpoa', 'list');
  }

  public function executeList()
  {
    $this->actividad_poas = ActividadPoaPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->actividad_poa = ActividadPoaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->actividad_poa);
  }

  public function executeCreate()
  {
    $this->actividad_poa = new ActividadPoa();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->actividad_poa = ActividadPoaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->actividad_poa);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $actividad_poa = new ActividadPoa();
    }
    else
    {
      $actividad_poa = ActividadPoaPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($actividad_poa);
    }

    $actividad_poa->setId($this->getRequestParameter('id'));
    $actividad_poa->setMetaPoaId($this->getRequestParameter('meta_poa_id') ? $this->getRequestParameter('meta_poa_id') : null);
    $actividad_poa->setProyectoId($this->getRequestParameter('proyecto_id') ? $this->getRequestParameter('proyecto_id') : null);
    $actividad_poa->setDescripcion($this->getRequestParameter('descripcion'));
    $actividad_poa->setResponsable($this->getRequestParameter('responsable'));
    $actividad_poa->setObservaciones($this->getRequestParameter('observaciones'));

    $actividad_poa->save();

    return $this->redirect('actividadpoa/show?id='.$actividad_poa->getId());
  }

  public function executeDelete()
  {
    $actividad_poa = ActividadPoaPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($actividad_poa);

    $actividad_poa->delete();

    return $this->redirect('actividadpoa/list');
  }
}
