<?php
// auto-generated by sfPropelCrud
// date: 2010/12/01 01:27:25
?>
<h1>actividadpoaproyecto</h1>

<table class="data">
<thead>
<tr>
  <th>Actividad</th>
  <th>Meta poa</th>
  <th>Proceso</th>
  <th>Tipo</th>
  <th>Procedimiento</th>
  <th>Proyecto</th>
  <th>Descripcion</th>
  <th>Responsable</th>
  <th>Observaciones</th>
</tr>
</thead>
<tbody>
<?php foreach ($actividad_poas as $actividad_poa): ?>
<tr>
    <td><?php echo link_to($actividad_poa->getActividadId(), 'actividadpoaproyecto/show?id='.$actividad_poa->getId()) ?></td>
      <td><?php echo $actividad_poa->getMetaPoaId() ?></td>
      <td><?php echo $actividad_poa->getProcesoId() ?></td>
      <td><?php echo $actividad_poa->getTipo() ?></td>
      <td><?php echo $actividad_poa->getProcedimientoId() ?></td>
      <td><?php echo $actividad_poa->getProyectoId() ?></td>
      <td><?php echo $actividad_poa->getDescripcion() ?></td>
      <td><?php echo $actividad_poa->getResponsable() ?></td>
      <td><?php echo $actividad_poa->getObservaciones() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
