<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:15:59
?>
<h1>componentesector</h1>

<table class="data">
<thead>
<tr>
  <th>Id</th>
  <th>Componente sector</th>
</tr>
</thead>
<tbody>
<?php foreach ($componente_sectors as $componente_sector): ?>
<tr>
    <td><?php echo link_to($componente_sector->getId(), 'componentesector/show?id='.$componente_sector->getId()) ?></td>
      <td><?php echo $componente_sector->getComponenteSector() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'componentesector/create') ?>
