<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/07/13 17:31:49

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root@localhost/indicadores',
), 'propel');
$this->databases['propel'] = $database;
