<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/07/13 17:31:50
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'setup',
  ),
  'seguimiento' => 
  array (
    'is_secure' => true,
    'credentials' => 'insert',
  ),
  'updateseguimiento' => 
  array (
    'is_secure' => true,
    'credentials' => 'insert',
  ),
);
