<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:20:47
?>
<?php use_helper('Object') ?>

<?php echo form_tag('proyectoinv/update') ?>

<?php echo object_input_hidden_tag($proyecto_inversion, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Meta pd:</th>
  <td><?php echo object_select_tag($proyecto_inversion, 'getMetaPdId', array (
  'related_class' => 'MetaPd',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Codigo:</th>
  <td><?php echo object_input_tag($proyecto_inversion, 'getCodigo', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Proyecto:</th>
  <td><?php echo object_textarea_tag($proyecto_inversion, 'getProyecto', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($proyecto_inversion->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'proyectoinv/delete?id='.$proyecto_inversion->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'proyectoinv/show?id='.$proyecto_inversion->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'proyectoinv/list') ?>
<?php endif; ?>
</form>
