<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:20:47
?>
<h1>proyectoinv</h1>

<table class="data">
<thead>
<tr>
  <th>Id</th>
  <th>Meta pd</th>
  <th>Codigo</th>
  <th>Proyecto</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($proyecto_inversions as $proyecto_inversion): ?>
<tr>
    <td><?php echo link_to($proyecto_inversion->getId(), 'proyectoinv/show?id='.$proyecto_inversion->getId()) ?></td>
      <td><?php echo $proyecto_inversion->getMetaPdId() ?></td>
      <td><?php echo $proyecto_inversion->getCodigo() ?></td>
      <td><?php echo $proyecto_inversion->getProyecto() ?></td>
      <td><?php echo $proyecto_inversion->getCreatedAt() ?></td>
      <td><?php echo $proyecto_inversion->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'proyectoinv/create') ?>
