<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:20:47
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $proyecto_inversion->getId() ?></td>
</tr>
<tr>
<th>Meta pd: </th>
<td><?php echo $proyecto_inversion->getMetaPdId() ?></td>
</tr>
<tr>
<th>Codigo: </th>
<td><?php echo $proyecto_inversion->getCodigo() ?></td>
</tr>
<tr>
<th>Proyecto: </th>
<td><?php echo $proyecto_inversion->getProyecto() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $proyecto_inversion->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $proyecto_inversion->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'proyectoinv/edit?id='.$proyecto_inversion->getId()) ?>
&nbsp;<?php echo link_to('list', 'proyectoinv/list') ?>
