<?php
// auto-generated by sfPropelCrud
// date: 2010/07/02 09:19:41
?>
<h1>anualizacion</h1>

<table class="data">
<thead>
<tr>
  <th>Meta pd</th>
  <th>Anyo1</th>
  <th>Anyo2</th>
  <th>Anyo3</th>
  <th>Anyo4</th>
</tr>
</thead>
<tbody>
<?php foreach ($anualizacions as $anualizacion): ?>
<tr>
    <td><?php echo link_to($anualizacion->getMetaPd(), 'anualizacion/show?id='.$anualizacion->getId()) ?></td>
      <td><?php echo $anualizacion->getAnyo1() ?></td>
      <td><?php echo $anualizacion->getAnyo2() ?></td>
      <td><?php echo $anualizacion->getAnyo3() ?></td>
      <td><?php echo $anualizacion->getAnyo4() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
