<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:46
?>
<?php use_helper('Object') ?>

<?php echo form_tag('cdp/update') ?>

<?php echo object_input_hidden_tag($cdp, 'getId') ?>

<table class="data">
<tbody>
<tr>
  <th>Numero:</th>
  <td><?php echo object_input_tag($cdp, 'getNumero', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Fecha:</th>
  <td><?php echo object_input_date_tag($cdp, 'getFecha', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Monto:</th>
  <td><?php echo object_input_tag($cdp, 'getMonto', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($cdp->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'cdp/delete?id='.$cdp->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'cdp/show?id='.$cdp->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'cdp/list') ?>
<?php endif; ?>
</form>
