<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:46
?>
<?php use_helper('Object') ?>

<?php echo form_tag('cdp/update') ?>

<?php echo object_input_hidden_tag($cdp, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Numero:</th>
  <td><?php echo object_input_tag($cdp, 'getNumero', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Fecha:</th>
  <td><?php echo object_input_date_tag($cdp, 'getFecha', array (
  'rich' => true,
)) ?></td>
</tr>
<tr>
  <th>Monto:</th>
  <td><?php echo object_input_tag($cdp, 'getMonto', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($cdp->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'cdp/delete?id='.$cdp->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'cdp/show?id='.$cdp->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'cdp/list') ?>
<?php endif; ?>
</form>
