<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:22:22
?>
<h1>cdp</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Numero</th>
  <th>Fecha</th>
  <th>Monto</th>
</tr>
</thead>
<tbody>
<?php foreach ($cdps as $cdp): ?>
<tr>
    <td><?php echo link_to($cdp->getId(), 'cdp/show?id='.$cdp->getId()) ?></td>
      <td><?php echo $cdp->getNumero() ?></td>
      <td><?php echo $cdp->getFecha() ?></td>
      <td><?php echo $cdp->getMonto() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'cdp/create') ?>
