<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:46
?>
<h1>cdp</h1>

<table>
<thead>
<tr>
  <th>Numero</th>
  <th>Fecha</th>
  <th>Monto</th>
</tr>
</thead>
<tbody>
<?php foreach ($cdps as $cdp): ?>
<tr>
    <td><?php echo link_to($cdp->getNumero(), 'cdp/show?id='.$cdp->getId()) ?></td>
      <td><?php echo $cdp->getFecha() ?></td>
      <td><?php echo $cdp->getMonto() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
