<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:22:22
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $cdp->getId() ?></td>
</tr>
<tr>
<th>Numero: </th>
<td><?php echo $cdp->getNumero() ?></td>
</tr>
<tr>
<th>Fecha: </th>
<td><?php echo $cdp->getFecha() ?></td>
</tr>
<tr>
<th>Monto: </th>
<td><?php echo $cdp->getMonto() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'cdp/edit?id='.$cdp->getId()) ?>
&nbsp;<?php echo link_to('list', 'cdp/list') ?>
