<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:46
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $cdp->getId() ?></td>
</tr>
<tr>
<th>Numero: </th>
<td><?php echo $cdp->getNumero() ?></td>
</tr>
<tr>
<th>Fecha: </th>
<td><?php echo $cdp->getFecha() ?></td>
</tr>
<tr>
<th>Monto: </th>
<td><?php echo $cdp->getMonto() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'cdp/edit?id='.$cdp->getId(), 'class="button"') ?>
&nbsp;<?php echo link_to('Listar', 'cdp/list') ?>
