<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:24:39
?>
<?php use_helper('Object') ?>

<?php echo form_tag('fuente/update') ?>

<?php echo object_input_hidden_tag($fuente, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Codigo:</th>
  <td><?php echo object_input_tag($fuente, 'getCodigo', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Fuente:</th>
  <td><?php echo object_input_tag($fuente, 'getFuente', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($fuente->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'fuente/delete?id='.$fuente->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'fuente/show?id='.$fuente->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'fuente/list') ?>
<?php endif; ?>
</form>
