<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:03
?>
<?php use_helper('Object') ?>

<?php echo form_tag('fuente/update') ?>

<?php echo object_input_hidden_tag($fuente, 'getId') ?>

<table class="data">
<tbody>
<tr>
  <th>Codigo:</th>
  <td><?php echo object_input_tag($fuente, 'getCodigo', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Fuente:</th>
  <td><?php echo object_input_tag($fuente, 'getFuente', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($fuente->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'fuente/delete?id='.$fuente->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'fuente/show?id='.$fuente->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'fuente/list') ?>
<?php endif; ?>
</form>
