<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:03
?>
<h1>fuente</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Codigo</th>
  <th>Fuente</th>
</tr>
</thead>
<tbody>
<?php foreach ($fuentes as $fuente): ?>
<tr>
    <td><?php echo link_to($fuente->getId(), 'fuente/show?id='.$fuente->getId()) ?></td>
      <td><?php echo $fuente->getCodigo() ?></td>
      <td><?php echo $fuente->getFuente() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'fuente/create') ?>
