<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:14:03
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $fuente->getId() ?></td>
</tr>
<tr>
<th>Codigo: </th>
<td><?php echo $fuente->getCodigo() ?></td>
</tr>
<tr>
<th>Fuente: </th>
<td><?php echo $fuente->getFuente() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'fuente/edit?id='.$fuente->getId()) ?>
&nbsp;<?php echo link_to('list', 'fuente/list') ?>
