<?php
// auto-generated by sfPropelCrud
// date: 2010/06/29 22:24:39
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $fuente->getId() ?></td>
</tr>
<tr>
<th>Codigo: </th>
<td><?php echo $fuente->getCodigo() ?></td>
</tr>
<tr>
<th>Fuente: </th>
<td><?php echo $fuente->getFuente() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'fuente/edit?id='.$fuente->getId()) ?>
&nbsp;<?php echo link_to('list', 'fuente/list') ?>
