<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:15:44
?>
<?php use_helper('Object') ?>

<?php echo form_tag('tipogasto/update') ?>

<?php echo object_input_hidden_tag($tipo_gasto, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Tipo gasto:</th>
  <td><?php echo object_input_tag($tipo_gasto, 'getTipoGasto', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="buttons"> <?php echo submit_tag('Guardar', 'class="button"') ?>
<?php if ($tipo_gasto->getId()): ?>
  &nbsp;<?php echo link_to('Eliminar', 'tipogasto/delete?id='.$tipo_gasto->getId(), array('post'=>'true', 'confirm'=>'¿Esta seguro?', 'class'=>'button')) ?>
  &nbsp;<?php echo link_to('Cancelar', 'tipogasto/show?id='.$tipo_gasto->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancelar', 'tipogasto/list') ?>
<?php endif; ?>
</form>
