<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:15:44
?>
<?php use_helper('Object') ?>

<?php echo form_tag('tipogasto/update') ?>

<?php echo object_input_hidden_tag($tipo_gasto, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Tipo gasto:</th>
  <td><?php echo object_input_tag($tipo_gasto, 'getTipoGasto', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($tipo_gasto->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'tipogasto/delete?id='.$tipo_gasto->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'tipogasto/show?id='.$tipo_gasto->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'tipogasto/list') ?>
<?php endif; ?>
</form>
