<?php
// auto-generated by sfPropelCrud
// date: 2010/08/20 03:15:44
?>
<table class="data">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $tipo_gasto->getId() ?></td>
</tr>
<tr>
<th>Tipo gasto: </th>
<td><?php echo $tipo_gasto->getTipoGasto() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('Editar', 'tipogasto/edit?id='.$tipo_gasto->getId()) ?>
&nbsp;<?php echo link_to('Listar', 'tipogasto/list') ?>
